import subprocess, sys
H = sys.argv[1]
import os
src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'Nykle.win.lua')).read()
harness = open(H).read()
SHA = subprocess.run(["redis-cli", "-p", "6399", "-x", "SCRIPT", "LOAD"], input=harness.encode(), capture_output=True).stdout.decode().strip()
M = [
 ('force needs charge', 'local forced = (window or guard or peeking) and dt and exploit_active()', 'local forced = (window or guard or peeking) and dt'),
 ('no smart hold', 'local SMART_HOLD = 8\n', 'local SMART_HOLD = 0\n'),
 ('no force write', '                pcall(function() cmd.force_defensive = true end)\n            end\n        elseif', '            end\n        elseif'),
 ('smart only peek', 'local window = mode == "Smart" and (smart_window(now)', 'local window = mode == "Smart" and state == "Peek" and (smart_window(now)'),
 ('no vertical', '    return vz * t - 0.5 * GRAVITY * t * t', '    return 0'),
 ('no jump key', '    elseif cmd.in_jump == true then\n        vz = JUMP_SPEED', '    elseif false then\n        vz = JUMP_SPEED'),
 ('no gravity', '    return vz * t - 0.5 * GRAVITY * t * t', '    return vz * t'),
 ('standing smart', '["Standing"]     = { "Double tap", "On peek",', '["Standing"]     = { "Double tap", "Smart",'),
 ('air on peek', '["Air"]          = { "Double tap", "Smart",', '["Air"]          = { "Double tap", "On peek",'),
 ('hold ignores sight', '                and seen_by_enemy()\n', '\n'),
 ('hold forever', 'local RECHARGE_HOLD_MAX = 1.2', 'local RECHARGE_HOLD_MAX = 120'),
 ('hold per tick', '    if api.allow_charge == nil or recharge.held == not allowed then', '    if api.allow_charge == nil then'),
 ('hold hs uncalibrated', 'hold = (dt or recharge.hs_charges) and', 'hold = true and'),
 ('hs never calibrates', '                recharge.hs_charges = true\n', ''),
 ('hold full', 'and charge < 1 and since >= 0', 'and since >= 0'),
 ('hold without event', 'and since >= 0 and since <= RECHARGE_HOLD_MAX', 'and true'),
 ('no fd release event', '        recharge.released = globals.realtime\n', ''),
 ('hold during fd', 'and (dt or hs) and not fakeduck then', 'and (dt or hs) then'),
 ('hs percent always', '(charging and recharge.hs_charges) and', 'charging and'),
 ('hs color plain', 'and charge < 1) and CHARGING or WHITE', 'and charge < 1) and WHITE or WHITE'),
 ('res window big', 'local RESOLVER_WINDOW = 4', 'local RESOLVER_WINDOW = 40'),
 ('res window small', 'local RESOLVER_WINDOW = 4', 'local RESOLVER_WINDOW = 2'),
 ('res spread counts', '        elseif state == "spread" then\n            aim_stats.spread = aim_stats.spread + 1\n', '        elseif state == "spread" then\n            aim_stats.spread = aim_stats.spread + 1\n            result = "c"\n'),
 ('res hits ignored', '            else\n                result = "h"\n            end', '            end'),
 ('res lowers user', '    if level > (SAFE_POINT_RANK[resolver.user_safe] or 0) then', '    if level > 0 then'),
 ('res user cache always', '    if overridden.safe_points == nil then\n        resolver.user_safe', '    if true then\n        resolver.user_safe'),
 ('res no aim target', '        resolver.aim_target, resolver.aim_time = target, now\n', '        resolver.aim_time = now\n'),
 ('res aim hold long', 'local AIM_TARGET_HOLD = 1.5', 'local AIM_TARGET_HOLD = 150'),
 ('res dead aim target', '        if ok and alive then\n            return target', '        if ok then\n            return target'),
 ('res switch ignored', '    if menu.resolver:get() then\n        local key, entry', '    if true then\n        local key, entry'),
 ('res learns when off', 'if result == nil or entry == nil or not menu.resolver:get() then', 'if result == nil or entry == nil then'),
 ('res log always', 'if menu.resolver_log:get() and level ~= before then', 'if menu.resolver_log:get() then'),
 ('res log switch ignored', 'if menu.resolver_log:get() and level ~= before then', 'if level ~= before then'),
 ('res number target', '    if type(target) == "number" then\n        local ok, ent', '    if false then\n        local ok, ent'),
 ('res no indicator', '("RES %d %s"):format(current.resolver, why)', '("RESX %d %s"):format(current.resolver, why)'),
 ('res stats reset', 'stats, pending_misses, aim_stats = {}, {}, new_aim_stats()', 'stats, pending_misses = {}, {}'),
 ('res counts disabled', '    events.aim_ack:set(protect("aim_ack", function(e)\n        if not menu.enabled:get() then\n            return\n        end\n', '    events.aim_ack:set(protect("aim_ack", function(e)\n'),
 ('res other as spread', '        else\n            aim_stats.other = aim_stats.other + 1', '        else\n            aim_stats.spread = aim_stats.spread + 1'),
 ('state no air', 'if type(flags) == "number" and bit.band(flags, 1) == 0 then', 'if false then'),
 ('state no crouch', 'if type(duck) == "number" and duck > 0.6 then', 'if false then'),
 ('state no moving', 'if ok and type(speed) == "number" and speed > 6 then', 'if false then'),
 ('state at ack time', 'local enemy = shot ~= nil and shot.state or enemy_state(target)', 'local enemy = enemy_state(target)'),
 ('prior uncapped', 'return min(window_misses(entry.results), 1)', 'return min(window_misses(entry.results), 2)'),
 ('prior removed', 'return min(window_misses(entry.results), 1)', 'return 0'),
 ('no per state', '        level = entry_level(entry, state)\n        local list', '        level = min(window_misses(entry.results), 2)\n        local list'),
 ('stall never', 'local FORCE_STALL = 0.5', 'local FORCE_STALL = 1000'),
 ('stall 1s', 'local FORCE_STALL = 0.5', 'local FORCE_STALL = 1.0'),
 ('stall ignores sight', 'if stall.last ~= nil and exposure.now and not stall.relaxed then', 'if stall.last ~= nil and not stall.relaxed then'),
 ('stall not reset by fire', '        if stall.key ~= nil and stall.key == player_id(target) then\n            stall.visible = 0\n', '        if false then\n            stall.visible = 0\n'),
 ('stall not reset by ack', '        if stall.key == player_id(target) and stall.state == enemy then\n            reset_stall', '        if false then\n            reset_stall'),
 ('stall keeps force', '    return stall.relaxed and 1 or level', '    return level'),
 ('stall log every tick', '        if stall.visible >= FORCE_STALL then\n            stall.relaxed = true', '        if stall.visible >= FORCE_STALL then\n            stall.visible = 0'),
 ('shot log switch ignored', '        if menu.shot_log:get() then\n            print(shot_line', '        if true then\n            print(shot_line'),
 ('shot log no log', '            print(shot_line(e, shot, target))\n', ''),
 ('shot state at ack', 'local state = shot ~= nil and shot.state or (target ~= nil and enemy_state(target)) or "?"', 'local state = (target ~= nil and enemy_state(target)) or "?"'),
 ('shot sp at ack', 'local safe = shot ~= nil and shot.safe or effective("safe_points")', 'local safe = effective("safe_points")'),
 ('shot fire fields lost', 'hitgroup = event_number(e, "hitgroup"), damage = event_number(e, "damage"),', 'hitgroup = nil, damage = nil,'),
 ('shot fire wins', '    local wanted = event_number(e, "wanted_hitgroup") or (shot and shot.hitgroup)\n    local wanted_damage', '    local wanted = (shot and shot.hitgroup) or event_number(e, "wanted_hitgroup")\n    local wanted_damage'),
 ('shot hc lost', 'hitchance ~= nil and ("%d%%"):format(round(hitchance)) or "?"', '"?"'),
 ('shot bt lost', 'backtrack ~= nil and ("%dt"):format(round(backtrack)) or "?"', '"?"'),
 ('delay random off', 'static_default and 0 or 1, nil, "t")', '0, nil, "t")'),
 ('delay random big', 'static_default and 0 or 1, nil, "t")', 'static_default and 0 or 2, nil, "t")'),
 ('delay random static', 'static_default and 0 or 1, nil, "t")', '1, nil, "t")'),
 ('protect prints every time', '        if not ok and not handler_errors[name] then', '        if not ok then'),
 ('protect silent', '            print(("[%s] %s hata verdi: %s"):format(SCRIPT, name, tostring(err)))\n', ''),
 ('threat cache off', '    if threat_cache.tick ~= tick then', '    if true then'),
 ('xuid ignored', 'if ok and type(xuid) == "string" and #xuid > 4 and xuid ~= "0" and not xuid:find("BOT", 1, true) then', 'if false then'),
 ('bot filter removed', ' and not xuid:find("BOT", 1, true) then', ' then'),
 ('memory cap off', 'local MEMORY_LIMIT = 64', 'local MEMORY_LIMIT = 6400'),
 ('brute seen not refreshed', '    if entry ~= nil then\n        entry.seen = globals.realtime\n    end\n    return brute_entry_stage(entry, group)', '    return brute_entry_stage(entry, group)'),
 ('map change wipes', '        reset_brute()\n        pending_misses = {}\n        resolver.shots, resolver.aim_target, resolver.prior_logged, resolver.jittery = {}, nil, {}, {}', '        brute.enemies = {}\n        resolver.players = {}\n        pending_misses = {}\n        resolver.shots, resolver.aim_target, resolver.prior_logged, resolver.jittery = {}, nil, {}, {}'),
 ('forget noop', '    resolver.players, resolver.shots, resolver.aim_target, resolver.prior_logged = {}, {}, nil, {}\n', ''),
 ('others ignored', '        return exposure.now or exposure.soon or exposure.any or shot_recently(32)\n', '        return exposure.now or exposure.soon or shot_recently(32)\n'),
 ('shot sight off', '        return exposure.now or exposure.soon or exposure.any or shot_recently(32)\n', '        return exposure.now or exposure.soon or exposure.any\n'),
 ('absent kept', '        if not present[index] or now < seen or now - seen > OTHER_HOLD then', '        if now < seen or now - seen > OTHER_HOLD then'),
 ('other hold zero', 'local OTHER_HOLD = 12', 'local OTHER_HOLD = 0'),
 ('dormant flanker', '            if index ~= nil and index ~= threat_index and ok_alive and alive and not dormant(enemy) then', '            if index ~= nil and index ~= threat_index and ok_alive and alive then'),
 ('vis ignores others', '        if exposure.now or exposure.any then\n            vis_color = accent', '        if exposure.now then\n            vis_color = accent'),
 ('recharge ignores others', '            hold = (dt or recharge.hs_charges) and charge < 1 and since >= 0 and since <= RECHARGE_HOLD_MAX\n                and seen_by_enemy()', '            hold = (dt or recharge.hs_charges) and charge < 1 and since >= 0 and since <= RECHARGE_HOLD_MAX\n                and (exposure.now or exposure.soon)'),
 ('hs ignores others', '        if on_peek and hs and (state == "Peek" or moving or seen_by_enemy() or exposure.peeking ~= nil) then', '        if on_peek and hs and (state == "Peek" or moving or exposure.now or exposure.soon or exposure.peeking ~= nil) then'),
 ('no release death', '        reset_brute()\n        set_charge(true)\n', '        reset_brute()\n'),
 ('no release round', '    pending_misses = {}\n    set_charge(true)\n    persist.save(false)', '    pending_misses = {}\n    persist.save(false)'),
 ('no release disable', '        reset_overrides()\n        set_charge(true)\n        return', '        reset_overrides()\n        return'),
 ('no release shutdown', '    reset_overrides()\n    set_charge(true)\n    persist.save(true)', '    reset_overrides()\n    persist.save(true)'),
 ('safe recharge switch ignored', '    if menu.safe_recharge:get() and exposure.available', '    if exposure.available'),
 ('held sampled', '    if dt and recharge.held then\n        return\n    end\n', ''),
 ('no zorla', '(current.forced and " (zorla)" or "")', '""'),
 ('no sarj bekle', '        parts[#parts + 1] = "sarj bekle"\n', ''),
 ('fd overwrite', '    if effective("fakeduck") then\n        parts[#parts + 1] = "FD"\n    end\n    parts[#parts + 1] = exploit\n    parts[#parts + 1] = (defensive_active()', '    parts[#parts + 1] = exploit\n    if effective("fakeduck") then\n        table.insert(parts, 1, "FD")\n    end\n    parts[2] = (defensive_active()'),
 ('forced not shown', 'current.defensive = (not on_peek and not clean) or hs_peek or forced', 'current.defensive = (not on_peek and not clean) or hs_peek'),
 ('smart hs break lc lost', 'local on_peek = mode == "On peek" or mode == "Smart"', 'local on_peek = mode == "On peek"'),
 ('rec not enforced', '    if rec.pending or tick < rec.tick or tick - rec.tick >= rec.every then', '    if rec.pending then'),
 ('rec every tick', 'every = 64, report = 30', 'every = 1, report = 30'),
 ('rec enforced when off', '            if on then\n                pcall(item.element.set', '            if true then\n                pcall(item.element.set'),
 ('rec silent', '        print(("[%s] %d ayar onerilen degerine donduruldu (orn. %s)"):format(SCRIPT, count, example))\n', ''),
 ('rec report spam', 'if now < rec.reported or now - rec.reported >= rec.report then', 'if true then'),
 ('rec off silent', '        print(("[%s] Always use recommended settings kapali: %d ayar onerilenden farkli (orn. %s)"):format(\n            SCRIPT, count, example))\n', ''),
 ('rec off report every check', '    if not on and not rec.report_off then\n        return\n    end\n', ''),
 ('rec label lost', 'label = label_prefix .. style.plain(name)', 'label = style.plain(name)'),
 ('rec no post load', '            recommended_state.pending, recommended_state.report_off = true, true\n        end\n    end))', '        end\n    end))'),
 ('fd guard radius', 'local KNIFE_NEAR, KNIFE_FAR = 260, 360', 'local KNIFE_NEAR, KNIFE_FAR = 260, 260'),
 ('fd guard near big', 'local KNIFE_NEAR, KNIFE_FAR = 260, 360', 'local KNIFE_NEAR, KNIFE_FAR = 360, 360'),
 ('fd guard dormant', 'if ok_alive and alive and not dormant(enemy) and ok_class and MELEE[class] then', 'if ok_alive and alive and ok_class and MELEE[class] then'),
 ('fd guard dead', 'if ok_alive and alive and not dormant(enemy) and ok_class and MELEE[class] then', 'if not dormant(enemy) and ok_class and MELEE[class] then'),
 ('fd guard any weapon', 'and ok_class and MELEE[class] then', 'and ok_class then'),
 ('fd guard switch ignored', '        if not menu.fd_guard:get() then', '        if false then'),
 ('fd guard dead kept', '        set_charge(true)\n        override("fakeduck", nil)\n        return', '        set_charge(true)\n        return'),
 ('fd guard never releases', '            elseif not menu.fd_guard:get() or knife_enemy(lp, KNIFE_FAR) == nil then\n', '            elseif false then\n'),
 ('fd guard without fd', '        if not get("fakeduck") then\n            return\n        end\n', ''),
 ('fd guard silent', '                if menu.hit_log:get() then\n                    print(("[%s] fake duck birakildi: %s bicak/zeus ile %d birim yakinda"):format(', '                if false then\n                    print(("[%s] fake duck birakildi: %s bicak/zeus ile %d birim yakinda"):format('),
 ('fd state raw', '        if effective("fakeduck") then\n            return "Fake duck"', '        if refs.fakeduck ~= nil and refs.fakeduck.spec ~= nil and refs.fakeduck.spec.value then\n            return "Fake duck"'),
 ('melee counted', '    if not melee then\n        local entry = stat_for', '    if true then\n        local entry = stat_for'),
 ('melee brute', 'if e.hitgroup == 1 and not melee and menu.anti_brute:get() then', 'if e.hitgroup == 1 and menu.anti_brute:get() then'),
 ('melee taser', ' or weapon == "taser"', ''),
 ('baim no armor', 'if type(armor) ~= "number" or armor > 0 then', 'if true then'),
 ('baim no falloff', 'damage = damage * info[3] ^ (', 'damage = damage * 1 ^ ('),
 ('baim stomach', 'damage = damage * info[2] / 2', 'damage = damage * info[2] / 2 * 1.25'),
 ('baim user force', 'resolver.user_body == "Force" or ', ''),
 ('baim no default', '                elseif info[4] then\n                    wanted = "Default"', '                elseif false then\n                    wanted = "Default"'),
 ('baim switch ignored', 'if target ~= nil and menu.smart_baim:get() then', 'if target ~= nil then'),
 ('res target threat only', '    return brute_target()\nend', '    return current_threat()\nend'),
 ('baim cache always', '        if overridden.body_aim == nil then\n            resolver.user_body', '        if true then\n            resolver.user_body'),
 ('baim awp stats', 'CWeaponAWP    = { 115, 1.95, 0.99, true }', 'CWeaponAWP    = { 88, 1.7, 0.98, true }'),
 ('baim r8 missing', '        Revolver      = { 86, 1.864, 0.94, true },\n', ''),
 ('baim no indicator', '"BAIM")', '"BAIMX")'),
 ('baim dead health', 'if info ~= nil and type(health) == "number" and health > 0 then', 'if info ~= nil and type(health) == "number" then'),
 ('shot hp at ack', 'local health = shot ~= nil and shot.health or nil', 'local health = target ~= nil and prop(target, "m_iHealth") or nil'),
 ('shot weapon at ack', 'shot ~= nil and shot.weapon or weapon_label(), profile_text(profile))', 'weapon_label(), profile_text(profile))'),
 ('shot ba at ack', 'local body = shot ~= nil and shot.body or effective("body_aim")', 'local body = effective("body_aim")'),
 ('attacker no facing label', 'parts[#parts + 1] = "AA hedefi yok"', 'parts[#parts + 1] = "AA hedefi degil"'),
 ('sight recent huge', 'recent = 32 }', 'recent = 3200 }'),
 ('sight gap zero', 'gap = 24,', 'gap = 0,'),
 ('sight no threat', 'if exposure.now and threat_index ~= nil then\n                    mark_sight', 'if false then\n                    mark_sight'),
 ('sight no others', '                mark_sight(pick.index, now)\n', ''),
 ('sight wrong unit', '* tick_interval())', '* 1)'),
 ('brute target threat only', '    local threat = brute_target()\n', '    local threat = current_threat()\n'),
 ('brute target threat sight', 'if exposure.now or exposure.soon or not exposure.any then', 'if not exposure.any then'),
 ('brute target never threat', 'if exposure.now or exposure.soon or not exposure.any then', 'if not exposure.any and false then'),
 ('baim no dt rule', 'elseif not info[4] and dt_ready() and health <= 2 * chest then', 'elseif false then'),
 ('baim dt ignores charge', '        return type(charge) ~= "number" or charge >= 1\n    end\n\n    -- Once gercek hasar', '        return true\n    end\n\n    -- Once gercek hasar'),
 ('baim dt on snipers', 'elseif not info[4] and dt_ready() and', 'elseif dt_ready() and'),
 ('baim scar missing', '        CWeaponSCAR20 = { 80, 1.65, 0.98, false },\n', ''),
 ('baim deagle three', 'health <= 2 * chest', 'health <= 3 * chest'),
 ('baim level ignored', 'if wanted == nil and level >= 2 and gun', 'if wanted == nil and false and gun'),
 ('baim level one', 'if wanted == nil and level >= 2 and gun', 'if wanted == nil and level >= 1 and gun'),
 ('baim level snipers', 'and gun and not (info ~= nil and info[4]) then', 'and gun then'),
 ('baim level knife', 'and gun and not (info ~= nil and info[4]) then', 'and not (info ~= nil and info[4]) then'),
 ('baim relaxed level', '    apply_body_aim(lp, class, aim_target, resolver_raw)', '    apply_body_aim(lp, class, aim_target, current.resolver)'),
 ('soft hit counted', '            if (wanted == 1 or wanted == 8) and hit ~= nil and hit ~= 1 and hit ~= 8 then', '            if false then'),
 ('soft neck ignored', '            if (wanted == 1 or wanted == 8) and hit ~= nil and hit ~= 1 and hit ~= 8 then', '            if wanted == 1 and hit ~= nil and hit ~= 1 and hit ~= 8 then'),
 ('soft neck hit', '            if (wanted == 1 or wanted == 8) and hit ~= nil and hit ~= 1 and hit ~= 8 then', '            if (wanted == 1 or wanted == 8) and hit ~= nil and hit ~= 1 then'),
 ('soft fire wanted lost', 'local wanted = event_number(e, "wanted_hitgroup") or (shot and shot.hitgroup)\n            local hit', 'local wanted = event_number(e, "wanted_hitgroup")\n            local hit'),
 ('db never saves', '    if pcall(function() db[persist.key] = data end) then', '    if false then'),
 ('db always dirty', '        persist.dirty = false\n    end\nend', '    end\nend'),
 ('db no throttle', '(not force and now >= persist.saved and now - persist.saved < persist.every)', 'false'),
 ('db saves clean', '    if not persist.dirty or (not force', '    if (not force'),
 ('db saves names', 'local function steam_key(key)\n    return type(key) == "string" and key:sub(1, 2) == "s:"', 'local function steam_key(key)\n    return type(key) == "string"'),
 ('db resolver not dirty', '        window_push(entry.states[enemy], result)\n        persist.dirty = true\n', '        window_push(entry.states[enemy], result)\n'),
 ('db no round save', '    set_charge(true)\n    persist.save(false)\n', '    set_charge(true)\n'),
 ('db no map save', '        enemy_watch.list = {}\n        persist.save(true)\n', '        enemy_watch.list = {}\n'),
 ('db no shutdown save', '    set_charge(true)\n    persist.save(true)\nend))', '    set_charge(true)\nend))'),
 ('db forget keeps', '    pcall(function() db[persist.key] = nil end)\n', ''),
 ('db no load', '    local loaded = persist.load()\n', '    local loaded = 0\n'),
 ('db load bad base', 'and e.base >= 0 and e.base <= #BRUTE_PHASES and e.base == floor(e.base) then', 'then'),
 ('db load names', 'if count < MEMORY_LIMIT and steam_key(key) and type(e) == "table" and type(e.base)', 'if count < MEMORY_LIMIT and type(e) == "table" and type(e.base)'),
 ('db load any state', 'for _, state in ipairs({ "Standing", "Moving", "Crouch", "Air", "Fakeduck" }) do', 'for _, state in ipairs({ "Standing", "Moving", "Crouch", "Air", "Fakeduck", "Fly" }) do'),
 ('db load bad results', '            if list[i] == "c" or list[i] == "h" then', '            if list[i] ~= nil then'),
 ('db load no states', '                        if #list > 0 then\n                            entry.states[state] = list', '                        if false then\n                            entry.states[state] = list'),
 ('db aliasing', '            data.resolver[key] = { name = entry.name, results = copy(entry.results), states = states,', '            data.resolver[key] = { name = entry.name, results = entry.results, states = entry.states,'),
 ('db no count', 'loaded > 0 and (" (hafiza: %d oyuncu)"):format(loaded) or ""', '""'),
 ('watch no defensive', '                        local fake = sim < t.max_sim\n', '                        local fake = false\n'),
 ('watch max not raised', '                        else\n                            t.max_sim = sim\n', '                        else\n'),
 ('watch hold long', 'hold = 16, samples = 6,', 'hold = 160, samples = 6,'),
 ('watch hold zero', 'hold = 16, samples = 6,', 'hold = 0, samples = 6,'),
 ('watch prior low', 'samples = 6, jitter_prior = 35,', 'samples = 6, jitter_prior = 5,'),
 ('watch prior huge', 'samples = 6, jitter_prior = 35,', 'samples = 6, jitter_prior = 3500,'),
 ('watch samples long', 'hold = 16, samples = 6,', 'hold = 16, samples = 60,'),
 ('watch min samples', '        if #t.deltas >= 4 then', '        if #t.deltas >= 1 then'),
 ('watch no lc', '> 64 * 64 then\n                                t.lc_tick = now', '> 64 * 64 * 100 then\n                                t.lc_tick = now'),
 ('watch lc small', '> 64 * 64 then\n', '> 10 * 10 then\n'),
 ('watch no reset gap', 'if t == nil or abs(sim - t.max_sim) > 1 then', 'if t == nil then'),
 ('watch dormant kept', 'if index ~= nil and ok_alive and alive and not dormant(enemy) and type(sim) == "number" then', 'if index ~= nil and ok_alive and alive and type(sim) == "number" then'),
 ('watch no purge', '            if not present[index] then\n                enemy_watch.list[index] = nil', '            if false then\n                enemy_watch.list[index] = nil'),
 ('watch delta unwrapped', 'abs((yaw - t.yaw + 180) % 360 - 180)', 'abs(yaw - t.yaw)'),
 ('excuse ignored', '            if profile ~= nil and (profile.lc or profile.defensive_now) then', '            if false then'),
 ('excuse counted corr', '                aim_stats.other = aim_stats.other + 1\n            else\n                aim_stats.correction', '                aim_stats.correction = aim_stats.correction + 1\n            else\n                aim_stats.correction'),
 ('excuse profile at ack', '            local profile = shot ~= nil and shot.profile or nil\n', '            local profile = enemy_watch.profile(aim_target_entity(e.target))\n'),
 ('shot profile at ack', '        profile = shot.profile\n', '        profile = enemy_watch.profile(target)\n'),
 ('prior ignores data', '    if not data and level < 1 and jittery then', '    if level < 1 and jittery then'),
 ('prior log spam', '        if key ~= nil and not resolver.prior_logged[key] and menu.resolver_log:get() then', '        if key ~= nil and menu.resolver_log:get() then'),
 ('prior not reset on map', 'resolver.shots, resolver.aim_target, resolver.prior_logged, resolver.jittery = {}, nil, {}, {}', 'resolver.shots, resolver.aim_target, resolver.jittery = {}, nil, {}'),
 ('prior label', 'local why = current.res_prior and "JIT" or', 'local why = false and "JIT" or'),
 ('res state label', 'or (anim.labels[current.res_state] or "")', 'or ""'),
 ('profile statik threshold', '(profile.jitter >= 15 and', '(profile.jitter >= 75 and'),
 ('profile no def text', '        parts[#parts + 1] = "def"\n', ''),
 ('face never', '        target = duel or recent_shooter() or seeing_flanker() or (threat == nil and aa_threat() or nil)', '        target = duel or recent_shooter() or seeing_flanker()'),
 ('face sign', 'yaw_offset + yaw - view', 'yaw_offset + view - yaw'),
 ('face swap axes', '(theirs.y - mine.y, theirs.x - mine.x)', '(theirs.x - mine.x, theirs.y - mine.y)'),
 ('face ignores base', 'if yaw_base ~= "At Target" or freestand then', 'if freestand then'),
 ('face ignores fs', 'if yaw_base ~= "At Target" or freestand then', 'if yaw_base ~= "At Target" then'),
 ('face facing not set', '    exposure.facing = index_of(target)\n    return "Local View"', '    return "Local View"'),
 ('face not called', '        yaw_base, yaw_offset = face_target(cmd, lp, yaw_base, yaw_offset, freestand)\n', ''),
 ('nearest dormant', 'if ok_alive and alive and not dormant(enemy) and ok_pos and pos ~= nil then', 'if ok_alive and alive and ok_pos and pos ~= nil then'),
 ('nearest last', 'if distance < best then', 'if distance > -1 then'),
 ('exposure one other', 'for _ = 1, min(2, #candidates) do', 'for _ = 1, min(1, #candidates) do'),
 ('exposure nl threat', '        local threat = aa_threat()\n        local threat_index', '        local threat = current_threat()\n        local threat_index'),
 ('high ground nl threat', '    local function on_high_ground(lp)\n        local threat = aa_threat()', '    local function on_high_ground(lp)\n        local threat = current_threat()'),
 ('attacker facing ignored', 'elseif index ~= nil and exposure.facing == index then', 'elseif index ~= nil then'),
 ('random alternates', 'if s.body_yaw:get() == "Random" then', 'if false then'),
 ('random yaw not synced', 'if body == "Jitter" or body == "Random" then\n        yaw_side = flip.side', 'if body == "Jitter" then\n        yaw_side = flip.side'),
 ('random brute yaw', 'if body ~= "Jitter" and body ~= "Random" then', 'if body ~= "Jitter" then'),
 ('random delay hidden', 's.delay:visibility(body == "Jitter" or body == "Random")', 's.delay:visibility(body == "Jitter")'),
 ('random not default fd', 'if state == "Fake duck" or state == "Safe head" then\n        body_items = { "Random"', 'if state == "Safe head" then\n        body_items = { "Random"'),
 ('random not default safe', 'if state == "Fake duck" or state == "Safe head" then\n        body_items = { "Random"', 'if state == "Fake duck" then\n        body_items = { "Random"'),
 ('def excused again', '            if profile ~= nil and (profile.lc or profile.defensive_now) then', '            if profile ~= nil and (profile.lc or profile.defensive) then'),
 ('jitter memory off', 'jitter_prior = 35, jitter_memory = 60,', 'jitter_prior = 35, jitter_memory = 0,'),
 ('jitter memory forever', 'jitter_prior = 35, jitter_memory = 60,', 'jitter_prior = 35, jitter_memory = 6000,'),
 ('jitter memory not reset map', 'resolver.shots, resolver.aim_target, resolver.prior_logged, resolver.jittery = {}, nil, {}, {}', 'resolver.shots, resolver.aim_target, resolver.prior_logged = {}, nil, {}'),
 ('jitter memory not reset forget', '    resolver.jittery = {}\n', ''),
 ('phase hits off', '    if e.hitgroup == 1 and not melee then\n        record_phase(group, phase, true)\n', '    if e.hitgroup == 1 and not melee then\n'),
 ('phase hit wrong group', 'record_phase(group, phase, true)', 'record_phase(current.phase_group, phase, true)'),
 ('phase misses off', '                record_phase(miss.group, miss.applied, false)\n', ''),
 ('phase miss wrong group', '                record_phase(miss.group, miss.applied, false)\n', '                record_phase(current.phase_group, miss.applied, false)\n'),
 ('phase learned ignored', '    if entry.learned then\n        return entry.base\n    end\n    return brute.default', '    return brute.default'),
 ('phase default ignored', '    if entry.learned then\n        return entry.base\n    end\n    return brute.default', '    return entry.base'),
 ('phase fresh zero', '    if entry == nil then\n        return brute.default[group]\n    end', '    if entry == nil then\n        return 0\n    end'),
 ('phase margin zero', 'brute.phase_rate(stats[current_default]) - 0.1 - 1e-9 then', 'brute.phase_rate(stats[current_default]) - 1e-9 then'),
 ('phase prior weak', '(stat.hits + 2) / (stat.shots + 4)', '(stat.hits + 1) / (stat.shots + 2)'),
 ('phase no halving', '    if stat.shots > 40 then', '    if false then'),
 ('phase log silent', '            print(("[%s] AA (%s): en az vurulan faz %d (%d/%d kafa isabeti) -> verisi olmayan dusmanlara faz %d"):format(\n                SCRIPT, brute.group_label[group], best, floor(chosen.hits + 0.5), floor(chosen.shots + 0.5), best))\n', ''),
 ('phase random off', '        if phase.random then\n            side = flip.rand_side', '        if false then\n            side = flip.rand_side'),
 ('phase random never drawn', '    flip.rand_side = random(0, 1) == 1\n', ''),
 ('phase not saved', '            list[phase + 1] = { shots = stat.shots, hits = stat.hits }\n', ''),
 ('phase not loaded', '                    brute.phases[group][phase] = { shots = e.shots, hits = e.hits }\n', ''),
 ('phase load invalid', 'and e.hits >= 0 and e.hits <= e.shots and e.shots <= 1000 then\n                    brute.phases', 'then\n                    brute.phases'),
 ('sniper load invalid', 'and e.hits >= 0 and e.hits <= e.shots and e.shots <= 1000 then\n                sniper.stats', 'then\n                sniper.stats'),
 ('phase forget keeps', '    brute.enemies, brute.recent, brute.hurt = {}, nil, {}\n    brute.reset_phases()\n', '    brute.enemies, brute.recent, brute.hurt = {}, nil, {}\n'),
 ('phase panel no star', 'phase == brute.default[group] and "*" or ""', '""'),
 ('learned flag ignored on hit', '        enemy.base, enemy.learned = (phase + 1) % (#BRUTE_PHASES + 1), true', '        enemy.base = (phase + 1) % (#BRUTE_PHASES + 1)'),
 ('force never', 'wanted, lethal, stalled = body_stall(target), true, true', 'wanted, lethal, stalled = "Prefer", true, true'),
 ('force stall never relaxes', '            if stall.visible >= FORCE_STALL then\n                stall.relaxed = true\n            end\n        end\n        stall.last = now\n        return stall.relaxed', '            if false then\n                stall.relaxed = true\n            end\n        end\n        stall.last = now\n        return stall.relaxed'),
 ('force stall ignores sight', 'if stall.last ~= nil and (exposure.now or exposure.any) and not stall.relaxed then', 'if stall.last ~= nil and not stall.relaxed then'),
 ('force no reset on fire', '            body.visible, body.relaxed = 0, false\n', ''),
 ('force no reset when not lethal', '        if not stalled then\n            local stall = resolver.body_stall', '        if false then\n            local stall = resolver.body_stall'),
 ('hs lc only peek', 'if on_peek and hs and (state == "Peek" or moving or seen_by_enemy() or exposure.peeking ~= nil) then', 'if on_peek and hs and (state == "Peek" or seen_by_enemy() or exposure.peeking ~= nil) then'),
 ('moving includes standing', 'move_state ~= "Standing" and move_state ~= "Crouching" and move_state ~= "Fake duck", armed, current.clean)', 'move_state ~= "Fake duck", armed, current.clean)'),
 ('fs auto off', 'local auto = menu.fs_auto:get() and (move_state == "Standing" or move_state == "Crouching")', 'local auto = false'),
 ('fs auto moving', 'local auto = menu.fs_auto:get() and (move_state == "Standing" or move_state == "Crouching")', 'local auto = menu.fs_auto:get()'),
 ('fs auto no crouch', 'local auto = menu.fs_auto:get() and (move_state == "Standing" or move_state == "Crouching")', 'local auto = menu.fs_auto:get() and move_state == "Standing"'),
 ('fs auto switch ignored', 'local auto = menu.fs_auto:get() and', 'local auto = true and'),
 ('shot not seen', 'return exposure.now or exposure.soon or exposure.any or shot_recently(32)', 'return exposure.now or exposure.soon or exposure.any'),
 ('shot seen long', 'shot_recently(32)', 'shot_recently(320)'),
 ('shot face long', 'not shot_recently(64)', 'not shot_recently(640)'),
 ('shot face dormant', 'if ok and ok_alive and alive and not dormant(ent) then', 'if ok and ok_alive and alive then'),
 ('shot not recorded', '        exposure.shot = { index = index_of(shooter), tick = globals.tickcount }\n', ''),
 ('shot not cleared round', '    reset_brute()\n    exposure.shot = nil\n', '    reset_brute()\n'),
 ('shot not cleared map', '        reset_stall(nil, nil)\n        exposure.shot = nil\n', '        reset_stall(nil, nil)\n'),
 ('shooter no face', '        target = duel or recent_shooter() or seeing_flanker() or (threat == nil and aa_threat() or nil)', '        target = duel or seeing_flanker() or (threat == nil and aa_threat() or nil)'),
 ('shooter no brute', '    return duel_target() or recent_shooter() or seeing_flanker() or aa_threat()', '    return duel_target() or seeing_flanker() or aa_threat()'),
 ('shooter when threat sees', '        if exposure.now or exposure.soon or not shot_recently(64) then', '        if not shot_recently(64) then'),
 ('md off', '            min_damage = HP_PLUS_ONE\n', '            min_damage = nil\n'),
 ('md above hp', '            min_damage = HP_PLUS_ONE\n', '            min_damage = HP_PLUS_ONE + 10\n'),
 ('md lowers user', 'if type(resolver.user_md) == "number" and resolver.user_md >= min_damage then', 'if false then'),
 ('md all weapons', 'local sniper = menu.head_only:get() and WEAPONS[class] ~= nil and WEAPONS[class][4] and exposed', 'local sniper = menu.head_only:get() and WEAPONS[class] ~= nil and exposed'),
 ('md switch ignored', 'local sniper = menu.head_only:get() and WEAPONS[class]', 'local sniper = WEAPONS[class]'),
 ('md user cache always', '        if overridden.min_damage == nil then\n            resolver.user_md', '        if true then\n            resolver.user_md'),
 ('md indicator', '"HEAD")', '"HEADX")'),
 ('md shot log at ack', '        min_damage = shot.md\n', '        min_damage = effective("min_damage")\n'),
 ('sniper never switch', '    if sniper.choice == "hs" and dt < hs - 0.1 then\n        return "dt"', '    if false then\n        return "dt"'),
 ('sniper never back', '    elseif sniper.choice == "dt" and hs < dt - 0.1 then\n        return "hs"', '    elseif false then\n        return "hs"'),
 ('sniper margin zero', 'dt < hs - 0.1', 'dt < hs'),
 ('sniper not hit', '        sniper.record(shot_sniper, true)\n', ''),
 ('sniper not miss', '                sniper.record(miss.sniper, false)\n', ''),
 ('sniper any weapon', '    if not SNIPERS[class] or effective("fakeduck") then\n        return nil', '    if effective("fakeduck") then\n        return nil'),
 ('sniper auto ignored', '(sniper_setting == "Hide shots" or (sniper_setting == "Auto (learn)" and sniper.choice == "hs"))', '(sniper_setting == "Hide shots" or sniper_setting == "Auto (learn)")'),
 ('sniper not loaded', '                sniper.stats[mode] = { shots = e.shots, hits = e.hits }\n', ''),
 ('sniper forget keeps', '    sniper.stats = { hs = { shots = 0, hits = 0 }, dt = { shots = 0, hits = 0 } }\n    sniper.choice = "hs"\n', ''),
 ('sniper panel star', 'sniper.choice == "hs" and "*" or ""', '""'),
 ('group all still', '    return brute.group_of[state] or "still"', '    return "still"'),
 ('group v45 not migrated', 'or groups[brute.migrate[group]]) or data.phases', 'or groups[brute.migrate[group]]) or nil'),
 ('aip switch ignored', 'if not ai_peek.available or not menu.ai_peek:get() or not peek_key_held() then', 'if not ai_peek.available or not peek_key_held() then'),
 ('aip no key', 'if not ai_peek.available or not menu.ai_peek:get() or not peek_key_held() then', 'if not ai_peek.available or not menu.ai_peek:get() then'),
 ('aip air', '        if bit.band(lp.m_fFlags, 1) == 0 or cmd.in_jump == true or cmd.in_use == true\n', '        if cmd.in_jump == true or cmd.in_use == true\n'),
 ('aip knife', '        return class ~= nil and not MELEE[class] and class ~= "CC4" and not is_grenade(class)\n    end\n\n    local function usable', '        return class ~= nil\n    end\n\n    local function usable'),
 ('aip user ignored', 'if mine == nil or not allowed(lp, cmd, class) or user_moving(cmd) then', 'if mine == nil or not allowed(lp, cmd, class) then'),
 ('aip keys ignored', '                or cmd.in_forward == true or cmd.in_back == true or cmd.in_moveleft == true or cmd.in_moveright == true\n', '                or false\n'),
 ('aip shot ignored', 'if (ai_peek.mode == "go" or ai_peek.mode == "hold") and own.last_shot >= ai_peek.started then', 'if false then'),
 ('aip idle after shot', ' or now - own.last_shot < ai_peek.after_shot or not due then', ' or not due then'),
 ('aip dt charging', '        local charging_dt = effective("doubletap") and type(charge) == "number" and charge < 1\n', '        local charging_dt = false\n'),
 ('aip no walls', '                if not walkable(lp, mine, spot) then\n                    break\n                end\n', ''),
 ('aip no ground', '        return ok_ground and ground\n', '        return true\n'),
 ('aip hull ignored', 'vector(-15, -15, 0), vector(15, 15, 54), lp, MASK_PLAYERSOLID)) >= 1', 'vector(-15, -15, 0), vector(15, 15, 54), lp, MASK_PLAYERSOLID)) >= 0'),
 ('aip any damage', '                local damage = best_damage(lp, vector(spot.x, spot.y, spot.z + height), points, need)\n                if damage >= need then\n', '                local damage = best_damage(lp, vector(spot.x, spot.y, spot.z + height), points, need)\n                if damage > 0 then\n'),
 ('aip need hp only', '        return max(1, min(md, health))\n', '        return health\n'),
 ('aip md over 100', '            return health + md - 100\n', '            return health\n'),
 ('aip here ignored', '        if best_damage(lp, vector(mine.x, mine.y, mine.z + height), points, need) >= need then\n            return "here"\n        end\n', ''),
 ('aip never holds open', '                    if ai_peek.mode == "go" then\n                        ai_peek.mode, ai_peek.until_time = "hold", now + hold', '                    if false then\n                        ai_peek.mode, ai_peek.until_time = "hold", now + hold'),
 ('aip no slow', '        local speed = distance > 12 and 450 or distance * 30\n', '        local speed = 450\n'),
 ('aip side flip', 'local forward, side = math.cos(angle) * speed, -math.sin(angle) * speed', 'local forward, side = math.cos(angle) * speed, math.sin(angle) * speed'),
 ('aip forward flip', 'local forward, side = math.cos(angle) * speed, -math.sin(angle) * speed', 'local forward, side = -math.cos(angle) * speed, -math.sin(angle) * speed'),
 ('aip view ignored', 'math.rad(math.deg(atan2(dy, dx)) - view)', 'math.rad(math.deg(atan2(dy, dx)))'),
 ('aip sides swapped', '{ { -dy, dx, "sol" }, { dy, -dx, "sag" } }', '{ { dy, -dx, "sol" }, { -dy, dx, "sag" } }'),
 ('aip not nearest', '                if found ~= nil and step >= found.step then\n                    break\n                end\n', ''),
 ('aip no timeout', '            if enemy == nil or now > ai_peek.until_time then\n', '            if enemy == nil then\n'),
 ('aip dormant', '        if enemy == nil or dormant(enemy) then\n            return nil\n        end\n        local ok, alive = pcall(function() return enemy:is_alive() end)\n        return ok and alive and enemy or nil', '        if enemy == nil then\n            return nil\n        end\n        local ok, alive = pcall(function() return enemy:is_alive() end)\n        return ok and alive and enemy or nil'),
 ('aip log silent', '            print(("[%s] ai peek: %s %d birim -> %s (hasar %d)"):format(SCRIPT, result.side .. (result.back and "-geri" or ""), result.step,\n                player_name(enemy), floor(result.damage + 0.5)))\n', ''),
 ('aip indicator', '"AI PEEK")', '"AI PEEKX")'),
 ('aip round keeps', '    exposure.shot = nil\n    ai_peek.reset()\n    pending_misses = {}', '    exposure.shot = nil\n    pending_misses = {}'),
 ('aip no call', '    update_ai_peek(lp, cmd, class)\n', ''),
 ('aip arrival never', '            elseif move_to(cmd, mine, ai_peek.target) < 4 then\n', '            elseif move_to(cmd, mine, ai_peek.target) < 0 then\n'),
 ('aip back never ends', '            if ai_peek.home == nil or move_to(cmd, mine, ai_peek.home) < 6 or now > ai_peek.until_time then\n', '            if ai_peek.home == nil or now > ai_peek.until_time + 100 then\n'),
 ('sniper min off', '    if sniper.stats[sniper.choice].shots < sniper.min_shots then\n', '    if false then\n'),
 ('sniper min 5', 'choice = "hs", min_shots = 4 }', 'choice = "hs", min_shots = 5 }'),
 ('smart hold 0', '    local SMART_HOLD = 8\n    local smart', '    local SMART_HOLD = 0\n    local smart'),
 ('peek group merged', 'Peek = "peek",', 'Peek = "move",'),
 ('peek not migrated', '(groups[group] or groups[brute.migrate[group]])', 'groups[group]'),
 ('aip no block', '        if ai_peek.blocked ~= nil and index == ai_peek.blocked then\n            return\n        end\n', ''),
 ('aip block any enemy', 'if ai_peek.blocked ~= nil and index == ai_peek.blocked then', 'if ai_peek.blocked ~= nil then'),
 ('aip block at 3', '                if ai_peek.fails >= 2 then\n', '                if ai_peek.fails >= 3 then\n'),
 ('aip fails not per enemy', '        if index ~= ai_peek.enemy then\n            ai_peek.fails = 0\n        end\n', ''),
 ('aip reset keeps block', 'ai_peek.mode, ai_peek.home, ai_peek.target, ai_peek.fails, ai_peek.blocked = nil, nil, nil, 0, nil', 'ai_peek.mode, ai_peek.home, ai_peek.target, ai_peek.fails = nil, nil, nil, 0'),
 ('aip shot keeps fails', '            ai_peek.mode, ai_peek.target, ai_peek.fails, ai_peek.blocked = "back", nil, 0, nil\n', '            ai_peek.mode, ai_peek.target, ai_peek.blocked = "back", nil, nil\n'),
 ('aip reached not tracked', '            ai_peek.reached = max(ai_peek.reached, sqrt(rx * rx + ry * ry))\n', ''),
 ('aip give up silent', '            print(("[%s] ai peek: atis olmadi, %s (%d/%d birim gidildi) -> geri"):format(SCRIPT, reason,\n                floor(ai_peek.reached + 0.5), ai_peek.step))\n', ''),
 ('aip block silent', '                        print(("[%s] ai peek: 2 bos peek, bu dusmana Peek Assist tusuna yeniden basana kadar peek yok"):format(SCRIPT))\n', ''),
 ('aip r8 hold same', '        local hold = class == "Revolver" and ai_peek.hold_r8 or ai_peek.hold\n', '        local hold = ai_peek.hold\n'),
 ('aip hold long', 'hold = 0.5, hold_r8 = 0.75', 'hold = 0.75, hold_r8 = 0.75'),
 ('aip buttons off', '            cmd.in_moveright, cmd.in_moveleft = side > 1, side < -1\n', ''),
 ('aip stand buttons', '            cmd.in_forward, cmd.in_back, cmd.in_moveright, cmd.in_moveleft = false, false, false, false\n', ''),
 ('safe high default on', '    menu.safe_high  = gear:switch("High ground", false)', '    menu.safe_high  = gear:switch("High ground", true)'),
 ('aip result off', '        ai_peek.result(e, target ~= nil and player_name(target) or nil)\n', ''),
 ('aip fired off', '        ai_peek.fired(e.id, target)\n', ''),
 ('aip hit not counted', '            aim_stats.ai_hits = aim_stats.ai_hits + 1\n', ''),
 ('aip shots not counted', '        aim_stats.ai_shots = aim_stats.ai_shots + 1\n', ''),
 ('aip peeks not counted', '        aim_stats.ai_peeks = aim_stats.ai_peeks + 1\n', ''),
 ('aip empty not counted', '        aim_stats.ai_empty = aim_stats.ai_empty + 1\n', ''),
 ('aip hurt not counted', '        aim_stats.ai_hurt = aim_stats.ai_hurt + 1\n', ''),
 ('aip hurt any time', '        if ai_peek.mode == nil then\n            return\n        end\n        aim_stats.ai_hurt', '        aim_stats.ai_hurt'),
 ('aip hurt silent', '            print(("[%s] ai peek: peek sirasinda vuruldun (%s -%d, %s)"):format(SCRIPT, HITGROUPS[hitgroup] or "?",\n                tonumber(damage) or 0, attacker_name))\n', ''),
 ('aip cancel any mode', '        if ai_peek.mode ~= "go" and ai_peek.mode ~= "hold" then\n            return\n        end\n        if menu.shot_log:get() then\n            local why', '        if menu.shot_log:get() then\n            local why'),
 ('aip cancel reason', 'local why = user_moving(cmd) and "hareket tusu"', 'local why = false and "hareket tusu"'),
 ('aip cancel silent', '            print(("[%s] ai peek: iptal, %s"):format(SCRIPT, why))\n', ''),
 ('aip idle report off', '        report_idle(now)\n', ''),
 ('aip idle quiet 0', 'why = nil, quiet = 1.0,', 'why = nil, quiet = 0,'),
 ('aip idle repeated', '        ai_peek.reported = true\n        if menu.shot_log:get() then\n            print(("[%s] ai peek: peek yok', '        if menu.shot_log:get() then\n            print(("[%s] ai peek: peek yok'),
 ('aip idle not reset', '        ai_peek.held_since, ai_peek.reported, ai_peek.why, ai_peek.shot = nil, false, nil, false\n', '        ai_peek.shot = false\n'),
 ('aip timeout reason', 'enemy == nil and "hedef yok" or "sure doldu"', '"hedef yok"'),
 ('aip closed reason', 'why or ("aci kapandi, hasar %d/%d")', 'why or ("sure doldu %d/%d")'),
 ('aip here reason', '            if result == "here" then\n                ai_peek.why =', '            if false then\n                ai_peek.why ='),
 ('aip dt reason', '            ai_peek.why = "DT sarj oluyor"\n', ''),
 ('aip panel row off', '    if aim_stats.ai_peeks > 0 then\n', '    if false then\n'),
 ('unlearned ignored', '    if brute.unlearned[current.state] then\n        return nil\n    end\n    return current.phase_group', '    return current.phase_group'),
 ('hit special counted', '        group = brute.stat_group()\n    end', '        group = current.phase_group\n    end'),
 ('impact special counted', 'entry.shot_group, entry.shot_sniper = current.brute, brute.stat_group(),', 'entry.shot_group, entry.shot_sniper = current.brute, current.phase_group,'),
 ('miss special counted', 'group = brute.stat_group(), sniper = sniper.mode(current.weapon),', 'group = current.phase_group, sniper = sniper.mode(current.weapon),'),
 ('unlearned no safe head', 'brute.unlearned = { ["Safe head"] = true, Manual = true,', 'brute.unlearned = { Manual = true,'),
 ('peek pred off', '                    exposure.peeked = ahead ~= nil and head_visible_to(threat, ahead, head, 0, 0, 0)\n', '                    exposure.peeked = false\n'),
 ('peek pred not soon', '                    exposure.soon = exposure.peeked\n', ''),
 ('peek pred no lookahead', 'return vector(eye.x + vx * EXPOSE_LOOKAHEAD, eye.y + vy * EXPOSE_LOOKAHEAD, eye.z)', 'return vector(eye.x, eye.y, eye.z)'),
 ('others pred off', '                if ahead ~= nil and head_visible_to(pick.enemy, ahead, head, 0, 0, 0) then\n', '                if false then\n'),
 ('others pred marks sight', '                    exposure.others[pick.index] = now\n                    exposure.peeked = true\n', '                    exposure.others[pick.index] = now\n                    exposure.peeked = true\n                    mark_sight(pick.index, now)\n'),
 ('others pred no peeked', '                    exposure.peeked = true\n', ''),
 ('anti off', '        local guard = mode == "On peek" and menu.anti_peek:get() and anti_window(now, armed ~= false)\n', '        local guard = false\n'),
 ('anti switch ignored', 'local guard = mode == "On peek" and menu.anti_peek:get() and anti_window(now, armed ~= false)', 'local guard = mode == "On peek" and anti_window(now, armed ~= false)'),
 ('anti hold 0', '    local ANTI_HOLD = 16\n', '    local ANTI_HOLD = 0\n'),
 ('anti hold long', '    local ANTI_HOLD = 16\n', '    local ANTI_HOLD = 64\n'),
 ('anti peeked not reset', '        exposure.now, exposure.soon, exposure.peeked, exposure.enemy_peek = false, false, false, false\n', '        exposure.now, exposure.soon, exposure.enemy_peek = false, false, false\n'),
 ('aip peek assist kept', '        if ai_peek.mode ~= nil then\n            override("peek_assist", false)\n        else', '        if false then\n            override("peek_assist", false)\n        else'),
 ('aip peek assist never back', '        else\n            override("peek_assist", nil)\n        end\n        -- Defensive ve AA', '        end\n        -- Defensive ve AA'),
 ('aip no walk back after shot', '            ai_peek.mode, ai_peek.target, ai_peek.fails, ai_peek.blocked = "back", nil, 0, nil\n', '            ai_peek.mode, ai_peek.target, ai_peek.fails, ai_peek.blocked = nil, nil, 0, nil\n'),
 ('aip shot counted empty', '                if ai_peek.shot then\n                    -- Atisla biten peek bos sayilmaz.\n                    ai_peek.shot = false\n                    return\n                end\n', ''),
 ('aip reset keeps override', '        override("peek_assist", nil)\n    end\n\n    -- Tus quiet', '    end\n\n    -- Tus quiet'),
 ('key held binds ignored', '            if ok_bind and (name == "Peek Assist" or (ref ~= nil and ref == refs.peek_assist)) then\n                return active == true\n            end\n', ''),
 ('key held fallback false', '                return active == true\n            end\n        end\n    end\n    return true\nend', '                return active == true\n            end\n        end\n    end\n    return false\nend'),
 ('fd still off', '        if not menu.fd_still:get() then\n            return false\n        end\n        if bit.band(lp.m_fFlags, 1) == 0 then\n            return true\n        end', '        if true then\n            return false\n        end\n        if bit.band(lp.m_fFlags, 1) == 0 then\n            return true\n        end'),
 ('fd still air ignored', '        if bit.band(lp.m_fFlags, 1) == 0 then\n            return true\n        end\n        local ok, speed', '        local ok, speed'),
 ('fd still no hysteresis', '        if fd.why == "move" then\n            return speed > FD_STOP\n        end\n', ''),
 ('fd still low threshold', 'local FD_MOVE, FD_STOP, FD_GRACE = 40, 10, 10', 'local FD_MOVE, FD_STOP, FD_GRACE = 20, 10, 10'),
 ('fd still never back', '                if not pointless then\n                    override("fakeduck", nil)\n                    fd.why = nil\n                end\n', ''),
 ('fd still not released', '        if pointless then\n            override("fakeduck", false)\n', '        if false then\n            override("fakeduck", false)\n'),
 ('fd still log every time', 'and (now < fd.logged or now - fd.logged > 10) then', 'then'),
 ('fd still silent', '                    print(("[%s] fake duck birakildi: %s (fake duck DT/HS\'yi kapatir; yerinde dururken calisir)"):format(\n                        SCRIPT, bit.band(lp.m_fFlags, 1) == 0 and "havadasin" or "hareket ediyorsun"))\n', ''),
 ('tp off', '    api.teleport()\n', ''),
 ('tp on ground', '    if move_state ~= "Air" and move_state ~= "Air crouch" then\n        if teleport.count > 0', '    if false then\n        if teleport.count > 0'),
 ('tp count not reset', '        teleport.count, teleport.refilled = 0, false\n', '        teleport.refilled = false\n'),
 ('tp unseen', '    if not (exposure.now or exposure.soon or exposure.any) or effective("fakeduck") then', '    if effective("fakeduck") then'),
 ('tp in fake duck', '    if not (exposure.now or exposure.soon or exposure.any) or effective("fakeduck") then', '    if not (exposure.now or exposure.soon or exposure.any) then'),
 ('tp hs ignores check', '    if not dt and not (hs and teleport.hs_ok ~= false) then', '    if not dt and not hs then'),
 ('tp hs never', '    if not dt and not (hs and teleport.hs_ok ~= false) then', '    if not dt then'),
 ('tp no charge', '    if type(charge) == "number" and charge < 1 then\n        return\n    end\n    local ok, speed', '    local ok, speed'),
 ('tp slow', 'speed < teleport.min_speed or', 'speed < 0 or'),
 ('tp count not increased', '    teleport.count, teleport.last = teleport.count + 1, now\n', '    teleport.last = now\n'),
 ('tp max 2', 'max_jump = 1, land_guard = 0.35', 'max_jump = 2, land_guard = 0.35'),
 ('tp switch ignored', '    if teleport.count >= teleport.max_jump or not menu.air_teleport:get() or api.teleport == nil', '    if teleport.count >= teleport.max_jump or api.teleport == nil'),
 ('tp log silent', '        print(("[%s] teleport: havada goruldun, %s ile isinlanildi (%d. kez)"):format(SCRIPT, dt and "DT" or "HS",\n            teleport.count))\n', ''),
 ('tp marker off', '        parts[#parts + 1] = ("tp %.2fs"):format(since_tp)\n', ''),
 ('tp hs check skipped', '            teleport.hs_ok = charge < 0.99\n', '            teleport.hs_ok = true\n'),
 ('tp hs check inverted', '            teleport.hs_ok = charge < 0.99\n', '            teleport.hs_ok = charge >= 0.99\n'),
 ('tp hs log silent', '                print(("[%s] teleport: Hide shots ile calismiyor (sarj harcanmadi); sadece DT\'li silahlarda"):format(SCRIPT))\n', ''),
 ('tp hs not rechecked per map', '        teleport.hs_ok, teleport.pending = nil, nil\n', ''),
 ('tp hs no pending', '        teleport.pending = { tick = globals.tickcount }\n', ''),
 ('air lag off', '(smart_window(now) or (airborne and menu.air_lag:get()))', 'smart_window(now)'),
 ('air lag switch ignored', '(smart_window(now) or (airborne and menu.air_lag:get()))', '(smart_window(now) or airborne)'),
 ('air lag ground', '        local airborne = state == "Air" or state == "Air crouch"\n', '        local airborne = true\n'),
 ('air lag no crouch', '        local airborne = state == "Air" or state == "Air crouch"\n', '        local airborne = state == "Air"\n'),
 ('sniper air dt off', '        if sniper_hs and menu.sniper_air_dt:get() and (current.state == "Air" or current.state == "Air crouch") then\n', '        if false then\n'),
 ('sniper air dt switch ignored', 'if sniper_hs and menu.sniper_air_dt:get() and (current.state', 'if sniper_hs and (current.state'),
 ('sniper air dt no crouch', 'and (current.state == "Air" or current.state == "Air crouch") then\n            sniper_hs = false', 'and current.state == "Air" then\n            sniper_hs = false'),
 ('sniper air dt everywhere', 'and (current.state == "Air" or current.state == "Air crouch") then\n            sniper_hs = false', 'then\n            sniper_hs = false'),
 ('aip no spot recheck', '                    if ai_peek.mode == "go" and ai_peek.target ~= nil then\n', '                    if false then\n'),
 ('aip walk follows threat', '            local enemy = peek_enemy()\n', '            local enemy = enemy_target()\n'),
 ('aip here recheck off', '                if damage >= need then\n                    result = "here"\n', '                if false then\n                    result = "here"\n'),
 ('md hp plus one', '    local HP_PLUS_ONE = 101\n', '    local HP_PLUS_ONE = 100\n'),
 ('md sniper always', 'WEAPONS[class][4] and exposed\n', 'WEAPONS[class][4]\n'),
 ('md sniper exposure ignored', '        local exposed = not exposure.available or exposure.now or exposure.soon or exposure.any\n', '        local exposed = true\n'),
 ('md sniper force', '            wanted = "Prefer"\n            -- Gosterge', '            wanted = "Force"\n            -- Gosterge'),
 ('baim key ignored', '            resolver.user_body = bind_value("body_aim", resolver.user_body)\n', ''),
 ('baim key any bind', 'if ok_bind and ref ~= nil and ref == refs[name] and active == true and value ~= nil then', 'if ok_bind and active == true and value ~= nil then'),
 ('aip need not lethal', '        if menu.head_only:get() and SNIPERS[current.weapon] then\n            return health + 1\n        end\n', ''),
 ('md indicator target', '            lethal = type(health) == "number" and health > 0 and health <= chest_damage(lp, target, WEAPONS[class])\n', '            lethal = false\n'),
 ('unreg off', '        if (state == "unregistered shot" or state == "damage rejection" or state == "prediction error")\n            and resolver.unreg[lag] ~= nil then\n', '        if false then\n'),
 ('unreg any shot', '        local lag = shot ~= nil and shot.lag or nil\n', '        local lag = "DEF"\n'),
 ('unreg one enough', '            if #list >= 2 then\n                resolver.unreg[lag], resolver.pause[lag]', '            if #list >= 1 then\n                resolver.unreg[lag], resolver.pause[lag]'),
 ('unreg window ignored', '                if now >= t and now - t <= resolver.unreg_window then\n', '                if true then\n'),
 ('unreg pause ignored', 'local forced = (window or guard or peeking) and dt and exploit_active() and not paused', 'local forced = (window or guard or peeking) and dt and exploit_active()'),
 ('unreg pause forever', '    return stop ~= nil and real >= stop - resolver.unreg_pause and real < stop\n', '    return stop ~= nil and real >= stop - resolver.unreg_pause and real < stop + 1000\n'),
 ('unreg silent', '                if menu.shot_log:get() then\n                    local names = resolver.lag_names[lag]', '                if false then\n                    local names = resolver.lag_names[lag]'),
 ('unreg not recorded', '(current.clean and " temiz" or "")), lag = lag,', '(current.clean and " temiz" or "")), lag = nil,'),
 ('tp summary off', '            print(("[%s] teleport: bu ziplamada %d kez%s"):format(SCRIPT, teleport.count,\n                teleport.refilled and "" or " (sarj havada tekrar dolmadi)"))\n', ''),
 ('tp refilled never', '            teleport.refilled = true\n', ''),
 ('tp refilled not reset', '        teleport.count, teleport.refilled = 0, false\n', '        teleport.count = 0\n'),
 ('edge off', '    return hits(x + ex, y + ey) or hits(x - ex, y - ey)\n', '    return false\n'),
 ('edge first only', '    return hits(x + ex, y + ey) or hits(x - ex, y - ey)\n', '    return hits(x + ex, y + ey)\n'),
 ('edge second only', '    return hits(x + ex, y + ey) or hits(x - ex, y - ey)\n', '    return hits(x - ex, y - ey)\n'),
 ('edge size 0', 'edge = 3.5, peeking = nil,', 'edge = 0, peeking = nil,'),
 ('peek def default off', 'menu.peek_defensive = grp.peek:switch(style.title("shield-halved", "Defensive during AI peek"), true)', 'menu.peek_defensive = grp.peek:switch(style.title("shield-halved", "Defensive during AI peek"), false)'),
 ('peek def ignored', 'local forced = (window or guard or peeking) and dt', 'local forced = (window or guard) and dt'),
 ('peek def switch ignored', 'exposure.peeking ~= nil and menu.peek_defensive:get()', 'exposure.peeking ~= nil'),
 ('peeking incl back', 'exposure.peeking = (ai_peek.mode == "go" or ai_peek.mode == "hold") and ai_peek.enemy or nil', 'exposure.peeking = ai_peek.mode ~= nil and ai_peek.enemy or nil'),
 ('peeking go only', 'exposure.peeking = (ai_peek.mode == "go" or ai_peek.mode == "hold") and ai_peek.enemy or nil', 'exposure.peeking = ai_peek.mode == "go" and ai_peek.enemy or nil'),
 ('face peek off', '    if peeking ~= nil and index_of(peeking) ~= index_of(threat) then\n        target = peeking\n', '    if false then\n        target = peeking\n'),
 ('face peek same off', '    elseif peeking ~= nil and threat ~= nil and index_of(peeking) == index_of(threat) then\n        return yaw_base, yaw_offset\n', ''),
 ('no confirm', '            ai_peek.candidate = { enemy = index, side = result.side, tick = tick }\n            return\n', '            ai_peek.candidate = nil\n'),
 ('confirm any side', 'candidate.enemy ~= index or candidate.side ~= result.side\n', 'candidate.enemy ~= index\n'),
 ('confirm any enemy', 'if candidate == nil or candidate.enemy ~= index or candidate.side', 'if candidate == nil or candidate.side'),
 ('confirm never stale', '            or tick - candidate.tick > 3 * ai_peek.confirm_every then', '            or false then'),
 ('confirm slow', '(ai_peek.candidate ~= nil and ai_peek.confirm_every) or ai_peek.every', 'ai_peek.every'),
 ('candidate kept on miss', '            ai_peek.candidate = nil\n            if result == "here" then', '            if result == "here" then'),
 ('walk every 4', 'local gap = walking and ai_peek.walk_every or', 'local gap = walking and ai_peek.every or'),
 ('lost max 1', 'if ai_peek.lost >= ai_peek.lost_max then', 'if ai_peek.lost >= 1 then'),
 ('lost max 5', 'lost_max = 3, reach = 74', 'lost_max = 5, reach = 74'),
 ('lost not reset here', '                    ai_peek.lost = 0\n                    if ai_peek.mode == "go" then', '                    if ai_peek.mode == "go" then'),
 ('lost not reset spot', 'ai_peek.lost, ai_peek.target, ai_peek.step = 0, result.spot,', 'ai_peek.lost, ai_peek.target, ai_peek.step = ai_peek.lost, result.spot,'),
 ('lost not reset start', 'ai_peek.step, ai_peek.lost, ai_peek.faked = index, 0, result.step, 0, false', 'ai_peek.step, ai_peek.faked = index, 0, result.step, false'),
 ('why ignored', 'give_up(cmd, mine, now, (why or ("aci kapandi', 'give_up(cmd, mine, now, (nil or ("aci kapandi'),
 ('no damage in msg', '("aci kapandi, hasar %d/%d"):format(floor(damage + 0.5), need)', '"aci kapandi"'),
 ('no spot damage max', '                        damage = max(damage, at_spot)\n', ''),
 ('other side ok', '                    why, result = "aci sadece diger tarafta", nil\n', '                    why = nil\n'),
 ('no reach', '                    if far > ai_peek.reach then', '                    if false then'),
 ('reach 200', 'lost_max = 3, reach = 74', 'lost_max = 3, reach = 200'),
 ('no follow', '                    if ai_peek.mode == "hold" then\n                        ai_peek.mode, ai_peek.until_time = "go", max(ai_peek.until_time, now + 0.25)\n                    end\n', ''),
 ('follow no time', '"go", max(ai_peek.until_time, now + 0.25)', '"go", ai_peek.until_time'),
 ('follow step kept', 'result.spot, max(ai_peek.step, floor(far + 0.5))', 'result.spot, ai_peek.step'),
 ('no stomach', 'for _, body in ipairs({ { 5, 50 }, { 3, 40 } }) do', 'for _, body in ipairs({ { 5, 50 } }) do'),
 ('tp no land guard', ' or teleport.land_time(lp) < teleport.land_guard then', ' then'),
 ('tp land guard 0', 'max_jump = 1, land_guard = 0.35', 'max_jump = 1, land_guard = 0'),
 ('tp land no vz', 'return (vz + sqrt(vz * vz + 2 * GRAVITY * 400 * result.fraction)) / GRAVITY', 'return sqrt(2 * GRAVITY * 400 * result.fraction) / GRAVITY'),
 ('tp land no ground 0', '        if result.fraction >= 1 then\n            return huge\n', '        if result.fraction >= 1 then\n            return 0\n'),
 ('fd grace 1', 'local FD_MOVE, FD_STOP, FD_GRACE = 40, 10, 10', 'local FD_MOVE, FD_STOP, FD_GRACE = 40, 10, 1'),
 ('fd grace 20', 'local FD_MOVE, FD_STOP, FD_GRACE = 40, 10, 10', 'local FD_MOVE, FD_STOP, FD_GRACE = 40, 10, 20'),
 ('fd grace no reset', 'fd.moving = speed > FD_MOVE and fd.moving + 1 or 0', 'fd.moving = speed > FD_MOVE and fd.moving + 1 or fd.moving'),
 ('rej not counted', 'if (state == "unregistered shot" or state == "damage rejection" or state == "prediction error")', 'if (state == "unregistered shot" or state == "prediction error")'),
 ('unreg not counted', 'if (state == "unregistered shot" or state == "damage rejection" or state == "prediction error")', 'if (state == "damage rejection" or state == "prediction error")'),
 ('lc pause ignored', '        local lc_ok = not paused("LC")\n', '        local lc_ok = true\n'),
 ('def pause ignored', 'exploit_active() and not paused("DEF")', 'exploit_active()'),
 ('pause msg kind', '                        names[1], resolver.unreg_pause, names[2], #list, state))', '                        "defensive", resolver.unreg_pause, names[2], #list, state))'),
 ('lag mark off', 'weapon = weapon_label() .. (lag ~= nil and " " .. lag or (current.clean and " temiz" or "")), lag = lag,', 'weapon = weapon_label() .. (current.clean and " temiz" or ""), lag = lag,'),
 ('lc mark off', '        current.lc = break_lc and not dt\n', '        current.lc = false\n'),
 ('lag forced off', 'or (current.forced and "DEF")\n', 'or (false and "DEF")\n'),
 ('defensive now le', '            defensive_now = t.sim < t.max_sim,', '            defensive_now = t.sim <= t.max_sim,'),
 ('def body off', '                and (profile.defensive_now or profile.fakeduck) then', '                and profile.fakeduck then'),
 ('fd detect off', '            and duck > enemy_watch.fd_low and duck < enemy_watch.fd_high and choked >= enemy_watch.fd_choke\n', '            and false\n'),
 ('fd one update', '                            if t.fd_count >= 2 then', '                            if t.fd_count >= 1 then'),
 ('fd no choke', ' and choked >= enemy_watch.fd_choke\n', '\n'),
 ('fd full duck', 'duck > enemy_watch.fd_low and duck < enemy_watch.fd_high', 'duck > enemy_watch.fd_low'),
 ('fd zero duck', 'duck > enemy_watch.fd_low and duck < enemy_watch.fd_high', 'duck < enemy_watch.fd_high'),
 ('fd count not reset', '                        else\n                            t.fd_count = 0\n                        end', '                        end'),
 ('fd hold 1', 'fd_choke = 6, fd_hold = 32 }', 'fd_choke = 6, fd_hold = 1 }'),
 ('fd state off', '    if profile ~= nil and profile.fakeduck then\n        return "Fakeduck"\n', '    if false then\n        return "Fakeduck"\n'),
 ('fd res label', 'Air = "AIR", Fakeduck = "FD" }', 'Air = "AIR" }'),
 ('fd label data', 'Air = "AIR", Fakeduck = "FD" } }', 'Air = "AIR" } }'),
 ('fd state not loaded', '{ "Standing", "Moving", "Crouch", "Air", "Fakeduck" }', '{ "Standing", "Moving", "Crouch", "Air" }'),
 ('other seen off', '                    if other == nil then\n                        found =', '                    if true then\n                        found ='),
 ('watcher reason off', '            elseif watcher ~= nil then\n', '            elseif false then\n'),
 ('other self', 'if index_of(other) ~= index and ok_alive and alive and not dormant(other) then', 'if ok_alive and alive and not dormant(other) then'),
 ('faked ignored', '                if result == nil and faked then\n', '                if false then\n'),
 ('faked msg', '.. (ai_peek.faked and ", dusman defensive kullandi" or ""))', ')'),
 ('faked no now', '(profile.defensive_now or profile.defensive or profile.lc)', '(profile.defensive or profile.lc)'),
 ('faked no lc', '(profile.defensive_now or profile.defensive or profile.lc)', '(profile.defensive_now or profile.defensive)'),
 ('faked not reset', 'ai_peek.lost, ai_peek.faked = index, 0, result.step, 0, false', 'ai_peek.lost = index, 0, result.step, 0'),
 ('fd yaw random 0', 's.yaw_random    = grp.angles:slider("Yaw randomize", 0, 30, fd_state and 20 or 0, nil, DEG)', 's.yaw_random    = grp.angles:slider("Yaw randomize", 0, 30, 0, nil, DEG)'),
 ('fd limit random 0', 'slider("Limit randomize", 0, 30, fd_state and 10 or 0, nil, DEG)', 'slider("Limit randomize", 0, 30, 0, nil, DEG)'),
 ('fd head off', '        if ok_base and base ~= nil and head.z < base.z + 64 then\n', '        if false then\n'),
 ('fd head 50', '            head = vector(head.x, head.y, base.z + 64)\n', '            head = vector(head.x, head.y, base.z + 50)\n'),
 ('totals not saved', '                hits = entry.hits, misses = entry.misses }', '                hits = entry.hits }'),
 ('totals not loaded', '                        entry[field] = floor(n)\n', ''),
 ('totals invalid kept', 'if type(n) == "number" and n >= 0 and n <= 100000 then', 'if type(n) == "number" then'),
 ('hits not counted', '            entry.hits = (entry.hits or 0) + 1\n', ''),
 ('misses not counted', '            entry.misses = (entry.misses or 0) + 1\n', ''),
 ('panel default off', 'menu.res_panel   = style.tip(grp.panel:switch(style.title("chart-simple", "Resolver panel"), true),', 'menu.res_panel   = style.tip(grp.panel:switch(style.title("chart-simple", "Resolver panel"), false),'),
 ('panel off ignored', '    if menu.res_panel:get() then\n        safe_draw(', '    if true then\n        safe_draw('),
 ('hit no spread', 'return floor(resolve * (1 - spread) * (1 - other) * 100 + 0.5)', 'return floor(resolve * (1 - other) * 100 + 0.5)'),
 ('hit no other', 'return floor(resolve * (1 - spread) * (1 - other) * 100 + 0.5)', 'return floor(resolve * (1 - spread) * 100 + 0.5)'),
 ('death counted', 'local counted = state ~= "death" and state ~= "player death"', 'local counted = true'),
 ('spread as other', '            if state == "spread" then\n                entry.spread = (entry.spread or 0) + 1\n            elseif', '            if false then\n            elseif'),
 ('rated other not counted', '                aim_stats.rated_other = aim_stats.rated_other + 1\n', ''),
 ('panel no move', '            res_panel.x = max(0, min(screen.x - w, mouse.x - d.dx))\n            res_panel.y = max(0, min(screen.y - h, mouse.y - d.dy))\n', ''),
 ('panel no clamp', '            res_panel.x = max(0, min(screen.x - w, mouse.x - d.dx))\n', '            res_panel.x = mouse.x - d.dx\n'),
 ('panel no clamp y', '            res_panel.y = max(0, min(screen.y - h, mouse.y - d.dy))\n', '            res_panel.y = mouse.y - d.dy\n'),
 ('panel no size', '            res_panel.size = max(70, min(200, round(d.size * (d.w + mouse.x - d.mx) / d.w)))\n', ''),
 ('panel no save', '            menu.panel_x:set(round(res_panel.x / max(1, screen.x) * 1000))\n', ''),
 ('panel closed drags', '        if not open or not ok_mouse or mouse == nil then', '        if not ok_mouse or mouse == nil then'),
 ('panel no lock', '        if anim.panel.drag ~= nil then\n            return false\n        end', '        if false then\n            return false\n        end'),
 ('panel no grip', '            if mouse.x >= x + w - grip and mouse.x <= x + w and mouse.y >= y + h - grip and mouse.y <= y + h then', '            if false then'),
 ('fd body off', '                and (profile.defensive_now or profile.fakeduck) then', '                and profile.defensive_now then'),
 ('phase5 off', '    if phase ~= nil and phase.freestand and not brute.unlearned[state] then\n', '    if false then\n'),
 ('v1 phase5 in special states', '    if phase ~= nil and phase.freestand and not brute.unlearned[state] then\n', '    if phase ~= nil and phase.freestand then\n'),
 ('phase5 body jitter', '        body, body_fs = "Static", "Peek Fake"\n', '        body_fs = "Peek Fake"\n'),
 ('phase5 removed', '    { invert = false, scale = 1.0,  shift = 0, freestand = true },\n', ''),
 ('phase5 peek real', '        body, body_fs = "Static", "Peek Fake"\n', '        body, body_fs = "Static", "Peek Real"\n'),
 ('hidden sideways back', '["Moving"]       = { "Double tap", "Smart",     "Up",     "Random" },', '["Moving"]       = { "Double tap", "Smart",     "Up",     "Sideways" },'),
 ('crouch move switch', '["Crouch move"]  = { "Double tap", "Smart",     "Up",     "Random" },', '["Crouch move"]  = { "Double tap", "Smart",     "Switch", "Random" },'),
 ('summary off', '    own.summary()\n    own.shot_summary()\n    reset_brute()', '    own.shot_summary()\n    reset_brute()'),
 ('summary no reset', '    local r = own.round\n    own.round = nil\n', '    local r = own.round\n'),
 ('summary hit log ignored', '    if r == nil or not menu.hit_log:get() then', '    if r == nil then'),
 ('summary unseen off', 'own.count(current.state, phase, e.hitgroup == 1, info:find("gormedi", 1, true) ~= nil)', 'own.count(current.state, phase, e.hitgroup == 1, false)'),
 ('summary phases all', '    if head then\n        r.phases[stage]', '    if true then\n        r.phases[stage]'),
 ('summary head count', '    r.head = r.head + (head and 1 or 0)\n', ''),
 ('summary exploit hs', '(effective("doubletap") and "DT") or (effective("hideshots") and "HS")', '(effective("hideshots") and "HS") or (effective("doubletap") and "DT")'),
 ('lc marker off', '        if current.lc then\n            exploit = exploit .. " LC"\n', '        if false then\n            exploit = exploit .. " LC"\n'),
 ('lc marker always', '        if current.lc then\n            exploit = exploit .. " LC"\n', '        if true then\n            exploit = exploit .. " LC"\n'),
 ('sniper default hs', '{ "Auto (learn)", "Hide shots", "Same as state" }', '{ "Hide shots", "Auto (learn)", "Same as state" }'),
 ('live no history', '        local value = (hits + 3.2) / (hits + misses + 4)\n', '        local value = 0.8\n'),
 ('live def off', '            if profile.defensive_now then\n                value = value * 0.5\n', '            if false then\n                value = value * 0.5\n'),
 ('live lc off', '            if profile.lc then\n                value = value * 0.6\n', '            if false then\n                value = value * 0.6\n'),
 ('live jitter off', '                value = value * (1 - min(profile.jitter, 120) / 600)\n', ''),
 ('live air off', '        if state == "Air" or state == "Fakeduck" then\n            value = value * 0.9\n', '        if false then\n            value = value * 0.9\n'),
 ('live far2500 off', '        if far ~= nil and far >= 2500 then\n            value = value * 0.85\n', '        if false then\n            value = value * 0.85\n'),
 ('live far off', '        elseif far ~= nil and far >= 1500 then\n            value = value * 0.92\n', '        elseif false then\n            value = value * 0.92\n'),
 ('live level off', '        value = value * (1 + 0.05 * level)\n', ''),
 ('live smooth off', '            res_panel.shown = res_panel.shown + (live - res_panel.shown) * dt\n', '            res_panel.shown = live\n'),
 ('live no snap', '            if res_panel.shown_index ~= index then\n                res_panel.shown_index, res_panel.shown = index, live\n', '            if false then\n                res_panel.shown_index, res_panel.shown = index, live\n'),
 ('live short name', 'name = #name > 16 and name:sub(1, 15) .. "." or name', 'name = name'),
 ('live no target text', 'main, name, info, col = "--", "", "COZUM   hedef yok", DIM', 'main, name, info, col = "--", "", "COZUM", DIM'),
 ('live shadow off', '        render.text(font, vector(x + 1, y + 1), res_panel.SHADOW, nil, text)\n', ''),
 ('live frame margin', '        res_panel.w, res_panel.h = w + 4, h + 3\n', '        res_panel.w, res_panel.h = w, h\n'),
 ('live tint flat', '        if t < 0.5 then\n            a, b, t = res_panel.LOW, res_panel.MID, t * 2\n', '        if false then\n            a, b, t = res_panel.LOW, res_panel.MID, t * 2\n'),
 ('live hit uses resolve', 'return floor(resolve * (1 - spread) * (1 - other) * 100 + 0.5)', 'return floor((1 - spread) * (1 - other) * 100 + 0.5)'),
 ('live frame off', '        if open then\n            local accent = menu.accent:get()\n            if not pcall(render.rect_outline', '        if false then\n            local accent = menu.accent:get()\n            if not pcall(render.rect_outline'),
 ('v1 jitter from fake', '                        if not fake then\n                            if yaw ~= nil', '                        if true then\n                            if yaw ~= nil'),
 ('v1 fake yaw baseline', '                            t.yaw = yaw\n                        end\n                        t.sim, t.origin = sim, origin', '                        end\n                        t.sim, t.origin, t.yaw = sim, origin, yaw'),
 ('v1 def no label', 'parts[#parts + 1] = "def (sahte kayit)"', 'parts[#parts + 1] = "def"'),
 ('v1 no exploit label always', 'menu.no_exploit:visibility(on and builder[selected] ~= nil and builder[selected].def_mode == nil)', 'menu.no_exploit:visibility(on)'),
 ('v1 no exploit label never', 'menu.no_exploit:visibility(on and builder[selected] ~= nil and builder[selected].def_mode == nil)', 'menu.no_exploit:visibility(false)'),
 ('v1 peek def always shown', '    menu.peek_defensive:visibility(on and menu.ai_peek:get())\n', ''),
 ('v1 ai peek no callback', 'menu.enabled, menu.auto_exploit, menu.ai_peek, menu.indicators', 'menu.enabled, menu.auto_exploit, menu.indicators'),
 ('v1 logs tracked', 'menu.brute_log      = grp.console:switch(', 'menu.brute_log      = tracked(grp.console):switch('),
 ('v1 sidebar name', 'pcall(ui.sidebar, SCRIPT, "crown")', 'pcall(ui.sidebar, "ANT-A-M", "crown")'),
 ('v1 header hidden', 'style.header = grp.info:label(style.title("crown", ("%s  V%s"):format(SCRIPT, VERSION)))', 'menu.header = grp.info:label(style.title("crown", ("%s  V%s"):format(SCRIPT, VERSION)))'),
 ('v1 exploit column', 'grp.bexploit:combo("Exploit"', 'grp.angles:combo("Exploit"'),
 ('v1 logs in resolver tab', 'menu.resolver_log   = style.tip(grp.console:switch(', 'menu.resolver_log   = style.tip(grp.resolver:switch('),
 ('v1 version print', '"[%s] V%s yuklendi%s"', '"[%s] v%s yuklendi%s"'),
 ('v1 fd safe back', '    if level > (SAFE_POINT_RANK[resolver.user_safe] or 0) then\n        override("safe_points", SAFE_POINT_LEVELS[level])', '    if effective("fakeduck") then\n        level = max(level, 1)\n    end\n    if level > (SAFE_POINT_RANK[resolver.user_safe] or 0) then\n        override("safe_points", SAFE_POINT_LEVELS[level])'),
 ('v1 tp tag off', '(since_tp >= 0 and since_tp <= resolver.tp_window and "TP") or ', ''),
 ('v1 tp window long', 'tp_window = 0.3,', 'tp_window = 3,'),
 ('v1 tp pause ignored', ' or api.teleport == nil or resolver.paused("TP")\n', ' or api.teleport == nil\n'),
 ('v1 tp names', 'TP = { "teleport", "teleport sonrasi" }', 'TP = { "Break LC", "Hide shots Break LC" }'),
 ('v1 paused never', 'return stop ~= nil and real >= stop - resolver.unreg_pause and real < stop', 'return false'),
 ('tp land guard 0.2', 'max_jump = 1, land_guard = 0.35', 'max_jump = 1, land_guard = 0.2'),
 ('sniper air dt default on', 'style.title("crosshairs", "Snipers use DT in the air"), false)', 'style.title("crosshairs", "Snipers use DT in the air"), true)'),
 ('v1 chest trace off', '        if trace_bullet ~= nil then\n            local ok_eye, eye = pcall(function() return lp:get_eye_position() end)', '        if false then\n            local ok_eye, eye = pcall(function() return lp:get_eye_position() end)'),
 ('v1 chest trace head', 'target:get_hitbox_position(5)', 'target:get_hitbox_position(0)'),
 ('v1 chest trace ignored', '                if ok and type(traced) == "number" then\n                    return traced', '                if false then\n                    return traced'),
 ('v1 peek weapon ready ignored', 'local armed = weapon_ready(lp, ai_peek.lead)', 'local armed = true'),
 ('v1 peek lead long', 'high = 32,\n    lead = 0.15,', 'high = 32,\n    lead = 5,'),
 ('v1 peek clip ignored', 'if type(clip) == "number" and clip == 0 then\n            return false', 'if false then\n            return false'),
 ('v1 peek hs charge ignored', 'local charging_hs = not effective("doubletap") and effective("hideshots") and recharge.hs_charges', 'local charging_hs = false and recharge.hs_charges'),
 ('v1 peek diag off', 'if theirs.z - mine.z >= ai_peek.high then', 'if false then'),
 ('v1 peek diag always', 'if theirs.z - mine.z >= ai_peek.high then', 'if true then'),
 ('v1 peek diag label', 'result.side .. (result.back and "-geri" or "")', 'result.side'),
 ('v1 peek diag forward', 'dirs[3] = { (-dy - dx) * r, (dx - dy) * r, "sol", true }', 'dirs[3] = { (-dy + dx) * r, (dx + dy) * r, "sol", true }'),
 ('v1 anti visible off', 'if exposure.peeked or (exposure.enemy_peek and not armed) then', 'if exposure.peeked then'),
 ('v1 anti fresh off', 'if s ~= nil and now >= s.first and now - s.first <= exposure.fresh then', 'if false then'),
 ('v1 anti speed off', 'return ok and type(speed) == "number" and speed >= exposure.peek_speed', 'return false'),
 ('v1 anti speed low', 'fresh = 16, peek_speed = 120', 'fresh = 16, peek_speed = 40'),
 ('v1 anti fresh long', 'fresh = 16, peek_speed = 120', 'fresh = 64, peek_speed = 120'),
 ('v1 anti others off', 'exposure.enemy_peek = exposure.enemy_peek or peeking_us(pick.enemy, pick.index, now)', ''),
 ('v1 anti indicator off', 'render.text(FONT, vector(x, y), accent, "c", "ANTI-PEEK")', 'render.text(FONT, vector(x, y), accent, "c", "")'),
 ('v1 anti flag', 'current.anti = forced and guard', 'current.anti = false'),
 ('v1 anti reset', 'exposure.now, exposure.soon, exposure.peeked, exposure.enemy_peek = false, false, false, false', 'exposure.now, exposure.soon, exposure.peeked = false, false, false'),
 ('v1 cap off', '    if level > 1 and ((menu.head_only:get() and SNIPERS[current.weapon]) or not resolver.body_open(target)) then\n        return 1', '    if false then\n        return 1'),
 ('v1 cap ignores switch', 'if level > 1 and ((menu.head_only:get() and SNIPERS[current.weapon]) or', 'if level > 1 and ((SNIPERS[current.weapon]) or'),
 ('v1 cap all weapons', 'if level > 1 and ((menu.head_only:get() and SNIPERS[current.weapon]) or', 'if level > 1 and ((menu.head_only:get()) or'),
 ('v1 cap after stall', '        level = stall_level(resolver.cap(raw, target), key, state, entry)', '        level = stall_level(raw, key, state, entry)'),
 ('v1 peek key standing', 'if peek_key_held() and (motion.moving or exposure.peeking ~= nil) then', 'if peek_key_held() then'),
 ('v1 peek key ai', 'if peek_key_held() and (motion.moving or exposure.peeking ~= nil) then', 'if peek_key_held() and motion.moving then'),
 ('v1 standing hidden back', '["Standing"]     = { "Double tap", "On peek",   "Off",    "Off" },', '["Standing"]     = { "Double tap", "On peek",   "Up",     "Random" },'),
 ('v1 crouching hidden back', '["Crouching"]    = { "Double tap", "On peek",   "Off",    "Off" },', '["Crouching"]    = { "Double tap", "On peek",   "Up",     "Random" },'),
 ('v1 peek hidden back', '["Peek"]         = { "Double tap", "Smart",     "Off",    "Off" },', '["Peek"]         = { "Double tap", "Smart",     "Up",     "Random" },'),
 ('v1 anti armed ignored', 'if exposure.peeked or (exposure.enemy_peek and not armed) then', 'if exposure.peeked or exposure.enemy_peek then'),
 ('v1 armed not passed', 'move_state ~= "Fake duck", armed, current.clean)', 'move_state ~= "Fake duck", nil, current.clean)'),
 ('v1 hs lc ai peek', 'seen_by_enemy() or exposure.peeking ~= nil) then', 'seen_by_enemy()) then'),
 ('v1 cap body ignored', 'or not resolver.body_open(target)) then', ') then'),
 ('v1 body open head', '    for _, hitbox in ipairs({ 5, 3 }) do\n        local ok_box', '    for _, hitbox in ipairs({ 0 }) do\n        local ok_box'),
 ('v1 body open unreadable', '    return not readable\n', '    return false\n'),
 ('v1 duel off face', '        target = duel or recent_shooter() or seeing_flanker() or (threat == nil and aa_threat() or nil)', '        target = recent_shooter() or seeing_flanker() or (threat == nil and aa_threat() or nil)'),
 ('v1 duel hold long', 'duel = nil, duel_hold = 1.0 }', 'duel = nil, duel_hold = 100 }'),
 ('v1 duel no sight', '        return sees and ent or nil', '        return ent'),
 ('v1 duel not recorded', '        exposure.duel = { index = index_of(target), time = now }\n', ''),
 ('v1 duel threat skip', '        if duel ~= nil and threat ~= nil and index_of(duel) == index_of(threat) then\n            duel = nil', '        if false then\n            duel = nil'),
 ('v1 duel brute off', '    return duel_target() or recent_shooter() or seeing_flanker() or aa_threat()', '    return recent_shooter() or seeing_flanker() or aa_threat()'),
 ('v1 duel threat sight', '            sees = exposure.now or exposure.soon\n', '            sees = true\n'),
 ('v1 engaged force off', '            if lethal and target == resolver.aim_target and since >= 0 and since <= AIM_TARGET_HOLD then\n                wanted, stalled = body_stall(target), true', '            if false then\n                wanted, stalled = body_stall(target), true'),
 ('v1 engaged no lethal', 'if lethal and target == resolver.aim_target', 'if target == resolver.aim_target'),
 ('v1 engaged hold long', 'since >= 0 and since <= AIM_TARGET_HOLD then\n                wanted, stalled', 'since >= 0 then\n                wanted, stalled'),
 ('v1 fake body off', 'local body_only = sniper and fake and lethal and menu.fake_body:get() and not cooling', 'local body_only = false'),
 ('v1 fake body any weapon', 'local body_only = sniper and fake and', 'local body_only = fake and'),
 ('v1 fake body switch ignored', 'and fake and lethal and menu.fake_body:get() and not cooling', 'and fake and lethal and not cooling'),
 ('v1 fake body no cap', '            if f.ticks > f.max then\n                f.free_until, body_only = now + f.cooldown, false', '            if false then\n                f.free_until, body_only = now + f.cooldown, false'),
 ('v1 fake body no cooldown', 'local cooling = now >= f.free_until - f.cooldown and now < f.free_until', 'local cooling = false'),
 ('v1 fake body no reset', '        if not body_only then\n            f.ticks = 0\n        end', ''),
 ('v1 fake body cap 30', 'ticks = 0, max = 12, cooldown = 0.5,', 'ticks = 0, max = 30, cooldown = 0.5,'),
 ('v1 fake body head', 'body = { "Chest", "Stomach" } }', 'body = { "Head", "Chest", "Stomach" } }'),
 ('v1 fake body log off', '            print(("[%s] resolver: %s sahte kayitta (defensive): sniper oldurecek govdeye, kafa gercek kayda"):format(\n', '            print(("[%s] resolver: %s"):format(\n'),
 ('v1 fake indicator off', 'render.text(FONT, vector(x, y), CHARGING, "c", "DEF BODY")', 'render.text(FONT, vector(x, y), CHARGING, "c", "")'),
 ('v1 fake real ignored', '        local fake = profile ~= nil and profile.defensive_now', '        local fake = profile ~= nil'),
 ('v1 panel prior old', 'local value = (hits + 3.2) / (hits + misses + 4)', 'local value = (hits + 1.2) / (hits + misses + 2)'),
 ('clean off', '    if not menu.clean_shot:get() or not armed or target == nil then', '    if true then'),
 ('clean switch ignored', '    if not menu.clean_shot:get() or not armed or target == nil then', '    if not armed or target == nil then'),
 ('clean ignores ready', '    if not menu.clean_shot:get() or not armed or target == nil then', '    if not menu.clean_shot:get() or target == nil then'),
 ('clean default off', 'style.title("gun", "Clean shot (no lag while shooting)"), true)', 'style.title("gun", "Clean shot (no lag while shooting)"), false)'),
 ('clean no hold', 'local clean_shot = { every = 2, hold = 6,', 'local clean_shot = { every = 2, hold = 0,'),
 ('clean long hold', 'local clean_shot = { every = 2, hold = 6,', 'local clean_shot = { every = 2, hold = 60,'),
 ('clean any damage', '            if ok and type(damage) == "number" and damage >= need then', '            if ok and type(damage) == "number" and damage > 0 then'),
 ('clean md ignores hp', '        return (type(hp) == "number" and hp or 100) + md - 100', '        return md'),
 ('clean dormant ok', '    if trace_bullet == nil or dormant(target) then\n        return false\n    end\n    local ok_eye, eye = pcall(function() return lp:get_eye_position() end)\n    if not ok_eye or eye == nil then\n        return false\n    end\n    local need', '    if trace_bullet == nil then\n        return false\n    end\n    local ok_eye, eye = pcall(function() return lp:get_eye_position() end)\n    if not ok_eye or eye == nil then\n        return false\n    end\n    local need'),
 ('clean unreadable true', '                if ok and type(damage) == "number" and damage >= need then\n                    return true\n                end\n            end\n        end\n    end\n    return false', '                if ok and type(damage) == "number" and damage >= need then\n                    return true\n                end\n            end\n        end\n    end\n    return true'),
 ('clean head only', 'boxes = { 0, 5, 3 } }', 'boxes = { 0 } }'),
 ('clean keeps lc', 'local hs_peek = on_peek and hs and lc_ok and not clean and now <= hs_lc.until_tick', 'local hs_peek = on_peek and hs and lc_ok and now <= hs_lc.until_tick'),
 ('clean keeps force', 'and not paused("DEF") and not clean\n', 'and not paused("DEF")\n'),
 ('clean keeps hidden', '        if clean or (pitch == nil and yaw == nil) then', '        if pitch == nil and yaw == nil then'),
 ('clean keeps teleport', ' or resolver.paused("TP")\n        or current.clean then', ' or resolver.paused("TP")\n        or false then'),
 ('clean not passed', 'move_state ~= "Fake duck", armed, current.clean)', 'move_state ~= "Fake duck", armed, false)'),
 ('clean knife', 'armed and class ~= nil and not NON_GUNS[class]\n        and not is_grenade(class) and not effective("fakeduck"))', 'armed\n        and not effective("fakeduck"))'),
 ('clean during fd', '        and not is_grenade(class) and not effective("fakeduck"))', '        and not is_grenade(class))'),
 ('fd still default on', 'style.title("person", "Fake duck only when standing still"), false)', 'style.title("person", "Fake duck only when standing still"), true)'),
 ('clean not reset', '    current.defensive, current.forced, current.lc, current.anti, current.clean = false, false, false, false, false', '    current.defensive, current.forced, current.lc, current.anti = false, false, false, false'),
 ('clean no indicator', 'render.text(FONT, vector(x, y), accent, "c", "CLEAN SHOT")', 'render.text(FONT, vector(x, y), accent, "c", "")'),
 ('clean no log mark', '(current.clean and " temiz" or "")), lag = lag,', '""), lag = lag,'),
 ('clean target switch keeps', '        if index ~= clean_shot.index then\n            clean_shot.until_tick = -1000\n        end\n', ''),
 ('pred error no pause', 'or state == "damage rejection" or state == "prediction error")', 'or state == "damage rejection")'),
 ('lag stats swapped', '                aim_stats.lag_shots, aim_stats.lag_hits = aim_stats.lag_shots + 1, aim_stats.lag_hits + hit', '                aim_stats.clean_shots, aim_stats.clean_hits = aim_stats.clean_shots + 1, aim_stats.clean_hits + hit'),
 ('lag stats no hits', '            local hit = state == nil and 1 or 0\n            if lag ~= nil then\n                aim_stats.lag_shots', '            local hit = 0\n            if lag ~= nil then\n                aim_stats.lag_shots'),
 ('lag stats row off', '        render.text(FONT, vector(x, y), WHITE, nil, ("LAG   %d / %d   TEMIZ   %d / %d"):format(', '        render.text(FONT, vector(x, y), WHITE, nil, ("LAGX   %d / %d   TEMIZ   %d / %d"):format('),
 ('rated spread off', '                aim_stats.rated_spread = aim_stats.rated_spread + 1\n', ''),
 ('rated counts death', '        if counted then\n            aim_stats.rated = aim_stats.rated + 1', '        if true then\n            aim_stats.rated = aim_stats.rated + 1'),
 ('hit other prior big', 'local other_all = (g.rated_other + 1) / (g.rated + 12)', 'local other_all = (g.rated_other + 4) / (g.rated + 12)'),
 ('hit enemy raw', 'local other = ((entry ~= nil and entry.other or 0) + other_all * 6) / (shots + 6)', 'local other = ((entry ~= nil and entry.other or 0) + other_all * 0.01) / (shots + 0.01)'),
 ('phase prior old', '    return (stat.hits + 2.4) / (stat.shots + 8)', '    return (stat.hits + 2) / (stat.shots + 4)'),
 ('phase prior high', '    return (stat.hits + 2.4) / (stat.shots + 8)', '    return (stat.hits + 4) / (stat.shots + 8)'),
 ('phase uses sniper rate', '        local rate = brute.phase_rate(stats[phase])', '        local rate = brute.rate(stats[phase])'),
 ('phase eps off', 'brute.phase_rate(stats[current_default]) - 0.1 - 1e-9 then', 'brute.phase_rate(stats[current_default]) - 0.1 then'),
 ('phase no hysteresis', 'brute.phase_rate(stats[current_default]) - 0.1 - 1e-9 then', 'brute.phase_rate(stats[current_default]) then'),
 ('scan brute fallback ntthreat', '    return duel_target() or recent_shooter() or seeing_flanker() or aa_threat()', '    return duel_target() or recent_shooter() or seeing_flanker() or current_threat()'),
 ('scan face no flanker', '        target = duel or recent_shooter() or seeing_flanker() or (threat == nil and aa_threat() or nil)', '        target = duel or recent_shooter() or (threat == nil and aa_threat() or nil)'),
 ('scan face nearest always', '        target = duel or recent_shooter() or seeing_flanker() or (threat == nil and aa_threat() or nil)', '        target = duel or recent_shooter() or seeing_flanker() or aa_threat()'),
 ('scan learn own stage', '        phase = menu.anti_brute:get() and threat_stage(current.phase_group) or 0', '        phase = menu.anti_brute:get() and brute_entry_stage(enemy, current.phase_group) or 0'),
 ('scan learn stale', '        phase = menu.anti_brute:get() and threat_stage(current.phase_group) or 0', '        phase = current.brute'),
 ('scan learn shot own stage', '        phase, group, shot_sniper = enemy.shot_applied, enemy.shot_group, enemy.shot_sniper', '        phase, group, shot_sniper = enemy.shot_stage, enemy.shot_group, enemy.shot_sniper'),
 ('scan learn no plus', '        enemy.base, enemy.learned = (phase + 1) % (#BRUTE_PHASES + 1), true', '        enemy.base, enemy.learned = phase % (#BRUTE_PHASES + 1), true'),
 ('scan round phase', '        own.count(current.state, phase, e.hitgroup == 1, info:find("gormedi", 1, true) ~= nil)', '        own.count(current.state, 0, e.hitgroup == 1, info:find("gormedi", 1, true) ~= nil)'),
 ('aip body counts', '                if not point.head and damage * shots < points.health then', '                if false then'),
 ('aip body no dt', "        local shots = (effective(\"doubletap\") and not SNIPERS[current.weapon]) and 2 or 1", '        local shots = 1'),
 ('aip head filtered', '                if not point.head and damage * shots < points.health then', '                if damage * shots < points.health then'),
 ('aip hold no ext', '                    ai_peek.until_time, ai_peek.extended = ai_peek.until_time + ai_peek.def_wait, true', '                    ai_peek.extended = true'),
 ('aip hold ext repeat', '                    ai_peek.until_time, ai_peek.extended = ai_peek.until_time + ai_peek.def_wait, true', '                    ai_peek.until_time = ai_peek.until_time + ai_peek.def_wait'),
 ('aip hold ext real', '                if profile ~= nil and profile.defensive_now then', '                if profile ~= nil then'),
 ('aip ext not reset', '        ai_peek.extended = false\n', ''),
 ('kd off', '            count_kd("deaths")\n', ''),
 ('kd kills off', '            count_kd("kills")\n', ''),
 ('kd any death', '        if menu.enabled:get() and ok_enemy and enemy_attacker then', '        if menu.enabled:get() then'),
 ('kd any kill', '        if ok_victim and enemy_victim then', '        if ok_victim then'),
 ('kd row off', '                render.text(FONT, vector(x, y), WHITE, nil, ("%s   %d / %d"):format(state:upper(), entry.kills, entry.deaths))', '                render.text(FONT, vector(x, y), WHITE, nil, ("%s   %d / %d"):format(state:upper(), entry.deaths, entry.kills))'),
 ('round sum off', '    own.summary()\n    own.shot_summary()\n', '    own.summary()\n'),
 ('round sum death', '        if counted then\n            local r = own.shots_round', '        if true then\n            local r = own.shots_round'),
 ('round sum not cleared', '    local r = own.shots_round\n    own.shots_round = nil\n', '    local r = own.shots_round\n'),
 ('round sum unsorted', '            return a.n > b.n', '            return a.n < b.n'),
 ('round sum log ignored', '    if r == nil or not menu.shot_log:get() then', '    if r == nil then'),
 ('round sum clean swap', '                    r.clean, r.clean_hits = r.clean + 1, r.clean_hits + hit', '                    r.lag, r.lag_hits = r.lag + 1, r.lag_hits + hit'),
 ('fake body ignores lethal', 'local body_only = sniper and fake and lethal and menu.fake_body:get() and not cooling', 'local body_only = sniper and fake and menu.fake_body:get() and not cooling'),
 ('clean no edges', '            if hitbox == 0 then\n                for _, side in ipairs(side_points(point, eye, exposure.edge)) do', '            if false then\n                for _, side in ipairs(side_points(point, eye, exposure.edge)) do'),
 ('aip no edges', '        for _, edge in ipairs(edges) do\n            points[#points + 1] = { pos = edge, head = true }\n        end\n', ''),
 ('side points zero', '    local ex, ey = -sy / length * edge, sx / length * edge\n    return { vector(point.x + ex', '    local ex, ey = 0, 0\n    return { vector(point.x + ex'),
]
bad = 0
for name, old, new in M:
    if src.count(old) != 1:
        print("SKIP (pattern count %d): %s" % (src.count(old), name)); bad += 1; continue
    mutated = src.replace(old, new)
    r = subprocess.run(["redis-cli", "-p", "6399", "-x", "EVALSHA", SHA, "0", "none"], input=mutated.encode(), capture_output=True)
    out = r.stdout.decode()
    fails = [l for l in out.splitlines() if l.startswith("FAIL") or l.startswith("ERR")]
    killed = bool(fails) or "ALL PASSED" not in out
    for extra in ("v46", "nobinds"):
        if killed:
            break
        r = subprocess.run(["redis-cli", "-p", "6399", "-x", "EVALSHA", SHA, "0", extra], input=mutated.encode(), capture_output=True)
        out = r.stdout.decode()
        fails = [l for l in out.splitlines() if l.startswith("FAIL") or l.startswith("ERR")]
        killed = bool(fails) or "ALL PASSED" not in out
    print(("KILLED  " if killed else "SURVIVED") + " %-28s %s" % (name, (fails[0][:90] if fails else out.strip()[:90])))
    if not killed: bad += 1
print("survivors/skips:", bad)
